/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],
    //未分类：
    '\n									Eighth Time Dimension': '\n									时间维度8',
    '\n									Fifth Time Dimension': '\n									时间维度5',
    '\n									First Time Dimension': '\n									时间维度1',
    '\n									Fourth Infinity Dimension': '\n									无尽维度4',
    '\n									Fourth Time Dimension': '\n									时间维度4',
    '\n									Second Time Dimension': '\n									时间维度2',
    '\n									Seventh Time Dimension': '\n									时间维度7',
    '\n									Sixth Time Dimension': '\n									时间维度6',
    '\n									Third Time Dimension': '\n									时间维度3',
    '\n								First Black Hole Dimension': '\n								黑洞维度1',
    '\n								Fourth Black Hole Dimension': '\n								黑洞维度4',
    '\n								Fourth Infinity Dimension': '\n								无尽维度4',
    '\n								Second Black Hole Dimension': '\n								黑洞维度2',
    '\n								Third Black Hole Dimension': '\n								黑洞维度3',
    '\n							  Eighth Meta Dimension\n						 ': '\n							  元维度8\n						 ',
    '\n							  Fifth Meta Dimension\n						 ': '\n							  元维度5\n						 ',
    '\n							  First Meta Dimension\n						 ': '\n							  元维度1\n						 ',
    '\n							  Fourth Meta Dimension\n						 ': '\n							  元维度4\n						 ',
    '\n							  Second Meta Dimension\n						 ': '\n							  元维度2\n						 ',
    '\n							  Seventh Meta Dimension\n						 ': '\n							  元维度7\n						 ',
    '\n							  Sixth Meta Dimension\n						 ': '\n							  元维度6\n						 ',
    '\n							  Third Meta Dimension\n						 ': '\n							  元维度3\n						 ',
    '\n							Amount of eternities to wait until dilate time': '\n							经过X次永恒自动开始膨胀时间',
    '\n							Antimatter Galaxies: requires 80 Eight Dimension\n						': '\n							反物质星系: 需求维度80个维度8\n						',
    '\n							Dimension Shift: requires 20 Fourth Dimension\n						': '\n							维度转换: 需求20个维度4\n						',
    '\n							First Infinity Dimension"': '\n							无尽维度1"',
    '\n							Fourth Infinity Dimension': '\n							无尽维度4',
    '\n							Second Infinity Dimension': '\n							无尽维度2',
    '\n							Third Infinity Dimension': '\n							无尽维度3',
    '\n							Tickspeed Boost (0): requires 10 Fifth Dimensions\n						': '\n							时间间隔加成 (0): 需求10个维度5\n						',
    '\n						  Meta-Dimension Shift: requires 20 Fourth Meta Dimensions\n					 ': '\n						  元维度变换: 需求20个元维度5\n					 ',
    '\n					You have': '\n					你拥有',
    '\n				Mastery study cost multiplier': '\n				专精研究花费倍率',
    '\n				Total TT spent to mastery studies': '\n				总共投入在专精研究上的时间定理',
    '\n				You have': '\n				你拥有',
    '1e11x multiplier on all Infinity Dimensions': '所有无尽维度增幅1e11倍',
    '1e4x multiplier on all Time Dimensions': '所有时间维度增幅1e4倍',
    '1e616x multiplier on all normal dimensions': '所有普通维度增幅1e616倍',
    'Achievements': '成就',
    'After eternity you permanently keep 5% of your infinities': '永恒后会保留5%的无限次数',
    'All replicated galaxies are stronger and use the same formula.': '所有复制品星系会更强并且拥有相同的公式.',
    'Animations': '动画',
    'antimatter.': '反物质.',
    'Auto-Eternity': '自动永恒',
    'Auto-save interval': '自动存档间隔',
    'Auto: ON': '自动已开启',
    'Automatic replicanti galaxies are disabled, but you can get 50% more': '你无法自动购买复制品星系，作为补偿你可以获得50%额外的复制品星系',
    'Automation': '自动化',
    'Big Crunch': '大坍塌',
    'Big Crunch for x Infinity Points': '大坍塌以获取X点无限点数',
    'Black hole': '黑洞',
    'black hole power. Translated to': '黑洞力量. 转化为',
    'Blue power boosts Meta Dimensions.': '蓝色力量可以增幅元维度.',
    'blue-red gluons.': '蓝-红 胶子.',
    'Boost first 4 Time Dimensions based on your Eternity Points and Eternal Matter.': '基于你的永恒点数以及永恒物质增幅前4个时间维度.',
    'Boost the ex-dilation gain.': '增幅EX-时间膨胀的获取.',
    'Boost tickspeed reduction based on your Eternity Points and Time Shards.': '基于永恒点和时间碎片增幅时间间隔.',
    'Boost Time Dimensions 4 - 6 based on your Eternity Points and Space Shards.': '基于永恒点和空间碎片增幅时间维度4~6.',
    'Break Eternity': '打破永恒',
    'BREAK ETERNITY': '打破永恒',
    'Break Eternity only works if you big rip the universe again.': '打破永恒只在你撕裂宇宙时生效.',
    'Buff the black hole upgrade effect based on your Eternity points.': '基于永恒点增幅你的黑洞升级.',
    'Buy all time studies': '购买所有时间研究',
    'Buy Max': '购买最大',
    'Cancel dilation penalty for Normal Dimensions boost from replicanti.': '取消膨胀时间对普通维度来源于复制品的惩罚.',
    'Challenge records': '挑战记录',
    'Challenges': '挑战',
    'Changelog  ': '更新日志  ',
    'Confirmations': '确认',
    'Cost': '费用',
    'Cost: 0 Time Theorems': '费用: 0 时间定理',
    'Cost: 1 Time Theorem': '费用: 1 时间定理',
    'Cost: 1,000,000 Time Theorems': '费用: 1,000,000 时间定理',
    'Cost: 1,000,000,000 Time Theorems': '费用: 1,000,000,000 时间定理',
    'Cost: 10 EP': '费用: 10 永恒点',
    'Cost: 10,000,000 Time Theorems': '费用: 10,000,000 时间定理',
    'Cost: 100 Time Theorems': '费用: 100 时间定理',
    'Cost: 100,000,000 Time Theorems': '费用: 100,000,000 时间定理',
    'Cost: 115 Time Theorems': '费用: 115 时间定理',
    'Cost: 12 Time Theorems': '费用: 12 时间定理',
    'Cost: 120 Time Theorems': '费用: 120 时间定理',
    'Cost: 15 Time Theorems': '费用: 15 时间定理',
    'Cost: 150 Time Theorems': '费用: 150 时间定理',
    'Cost: 1e12000 EP': '费用: 1e12000 永恒点',
    'Cost: 1e1500 EP': '费用: 1e1500 永恒点',
    'Cost: 1e16 EP': '费用: 1e16 永恒点',
    'Cost: 1e20 dilated time': '费用: 1e20 膨胀时间',
    'Cost: 1e2000 EP': '费用: 1e2000 永恒点',
    'Cost: 1e20000 EP': '费用: 1e20000 永恒点',
    'Cost: 1e3000 EP': '费用: 1e3000 永恒点',
    'Cost: 1e40 EP': '费用: 1e40 永恒点',
    'Cost: 1e4000 EP': '费用: 1e4000 永恒点',
    'Cost: 1e5 dilated time': '费用: 1e5 膨胀时间',
    'Cost: 1e50 EP': '费用: 1e50 永恒点',
    'Cost: 1e6 dilated time': '费用: 1e6 膨胀时间',
    'Cost: 1e7 dilated time': '费用: 1e7 膨胀时间',
    'Cost: 1e8 dilated time': '费用: 1e8 膨胀时间',
    'Cost: 1e8000 EP': '费用: 1e8000 永恒点',
    'Cost: 1e9 dilated time': '费用: 1e9 膨胀时间',
    'Cost: 2 Time Theorems': '费用: 2 时间定理',
    'Cost: 20 Time Theorems': '费用: 20 时间定理',
    'Cost: 200 Time Theorems': '费用: 200 时间定理',
    'Cost: 25 Time Theorems': '费用: 25 时间定理',
    'Cost: 3 Time Theorems': '费用: 3 时间定理',
    'Cost: 300 Time Theorems': '费用: 300 时间定理',
    'Cost: 4 Time Theorems': '费用: 4 时间定理',
    'Cost: 400 Time Theorems': '费用: 400 时间定理',
    'Cost: 5 EP': '费用: 5 永恒点',
    'Cost: 5 Time Theorems': '费用: 5 时间定理',
    'Cost: 50 K EP': '费用: 50000 永恒点',
    'Cost: 500 EP': '费用: 500 永恒点',
    'Cost: 500 Time Theorems': '费用: 500 时间定理',
    'Cost: 5000 Time Theorems': '费用: 5000 时间定理',
    'Cost: 5e6 dilated time': '费用: 5e6 膨胀时间',
    'Cost: 5e7 dilated time': '费用: 5e7 膨胀时间',
    'Cost: 6 Time Theorems': '费用: 6 时间定理',
    'Cost: 7 Time Theorems': '费用: 7 时间定理',
    'Cost: 730 Time Theorems': '费用: 730 时间定理',
    'Cost: 8 Time Theorems': '费用: 8 时间定理',
    'Cost: 85 Time Theorems': '费用: 85 时间定理',
    'Cost: 9 Time Theorems': '费用: 9 时间定理',
    'Cost: 900 Time Theorems': '费用: 900 时间定理',
    'Cost: xx banked infinities': '费用: xx 储存的无限次数',
    'Cost: xx dilated time': '费用: xx 膨胀时间',
    'Cost: xx replicanti': '费用: xx 复制品',
    'Current IP multiplier': '无限点数获取倍率',
    'Current tickspeed upgrades': '时间间隔升级次数',
    'Decrease the galaxy threshold multiplier, but resets free galaxies and dilated time.': '减少星系的门槛，但是重置免费星系和膨胀时间',
    'Dilate time.': '膨胀时间',
    'dilated time': '膨胀时间',
    'Dilated time gain is boosted by antimatter': '基于反物质数量增幅膨胀时间的获取',
    'Dilated time gain is boosted by eternity points': '基于永恒点数量增幅膨胀时间的获取',
    'Dilated time gain is boosted by infinity points': '基于无限点数量增幅膨胀时间的获取',
    'Dilated time production is boosted based on best meta-antimatter.': '基于最佳元-反物质数量增幅膨胀时间的获取',
    'dilated time, gained total of': '总共获取的膨胀时间',
    'Dilation options': '膨胀时间选项',
    'Dimension boost multiplier is incremented': '维度提升倍率是递增的',
    'Dimensional boost costs scale by another 1 less.': '维度提升费用降低1',
    'Dimensional boost costs scale by another 2 less.': '维度提升费用降低2',
    'Dimensional boost requirement scaling is reduced by': '维度提升费用降低',
    'Dimensional boosts affect Infinity Dimensions': '维度提升影响无限维度',
    'Dimensional boosts affect Meta Dimensions at reduced rate.': '维度提升以更低的效率影响元维度',
    'Dimensional boosts affect time dimensions with reduced power.': '维度提升以更低的效率影响时间维度',
    'Dimensional boosts are 0.04% more effective for each tick upgrade gained from Time Dimensions': '每拥有一个来源于时间维度的时间间隔升级维度提升提升0.04%的效率',
    'Dimensional boosts are more effective based on their amount.': '基于维度提升的次数维度提升将会更强',
    'Dimensional Sacrifice': '维度献祭',
    'Dimensions': '维度',
    'Disable hotkeys': '禁用快捷键',
    'Distribute ex-dilation': '分配EX-膨胀时间',
    'Divide normal galaxy cost in Eternity Challenge 10 based on your Eternal Matter.': '基于永恒物质的数量降低普通星系在永恒挑战10中的费用',
    'Divide the normal galaxy cost based on your Eternity Points.': '基于永恒点数降低普通星系的费用',
    'Double the dilated time production.': '膨胀时间产出*2',
    'Eighth Dimensions boost Meta Dimensions.': '维度8会增幅元维度',
    'Emperor Dimensions': '帝国维度',
    'Emperor Dimensions and hatch speed are faster by 25x.': '帝国维度以及孵化效率增幅25倍',
    'Enable': '启用',
    'enabled': '禁用',
    'Eternal Matter': '永恒物质',
    'Eternal Matter.': '永恒物质',
    'Eternities and dilated time boost each other by ^0.1.': '永恒次数与膨胀时间互相提升彼此效果 倍率^0.1',
    'Eternities and dilated time power up each other.': '永恒次数与膨胀时间互相提升彼此效果',
    'Eternity': '永恒',
    'Eternity Challenge': '永恒挑战',
    'Eternity Challenge records': '永恒挑战记录',
    'Eternity milestones': '永恒里程碑',
    'Eternity Points': '永恒点数',
    'Eternity upgrades': '永恒升级',
    'ex-dilation,': 'EX-膨胀时间',
    'Exponents of antimatter per second': '反物质每秒的指数',
    'Export': '导出',
    'Export "Infinite" bug save': '导出无限bug存档',
    'Export spec': '导出永恒专精',
    'Export tree': '导出永恒树',
    'extra seconds after matter exceeds your antimatter amount.': '正物质超过反物质的额外秒数',
    'Feed the black hole with banked infinities': '用储存的无尽次数填充黑洞',
    'Feed the black hole with dilated time': '用膨胀时间填充黑洞',
    'Feed the black hole with replicanti': '用复制品填充黑洞',
    'Free galaxies are as strong as a normal replicated galaxy.': '免费星系将会和普通复制品星系一样强',
    'free galaxy': '免费星系',
    'Gain 5% more Tachyon particles for each': '每个增加5%超光速粒子的获取',
    'Gain a multiplier to IP based on dilated time.': '基于膨胀时间获得无限点获取增幅',
    'Gain a multiplier to meta-dimensions based on tickspeed.': '基于时间间隔增幅元维度',
    'Gain twice as many free galaxies.': '获取双倍的免费星系',
    'Galaxies are more effective based on non-replicated galaxies.': '基于非复制品星系的数量增幅星系效果',
    'Galaxies are more effective based on your timeshards': '基于时间碎片的数量增幅星系效果',
    'Galaxy': '星系',
    'Galaxy cost scaling starts 1 galaxy later for every 2000 dimensional boosts.': '每拥有2000个维度提升 遥远星系将会延迟1个普通星系',
    'Galaxy cost scaling starts 7 galaxies later.': '遥远星系将会在额外7个普通星系之后',
    'Galaxy points.': '星系点',
    'Generate time theorems based on tachyon particles.': '基于超光速粒子的数量自动生成时间定理',
    'Get x antimatter to unlock a new Dimension.': '到达x个反物质解锁一个新的维度',
    'Ghost Particles.': '幽灵粒子',
    'Ghostify': '幽灵',
    'green-blue, and': '绿-蓝，和',
    'Hatch speed is faster based on your extra replicated galaxies.': '基于你的额外复制品星系数量增幅孵化速度',
    'Hatch speed is faster based on your meta-antimatter.': '基于你的元维度数量增幅孵化速度',
    'Hatch speed is faster based on your tachyon particles.': '基于你的超光速粒子数量增幅孵化速度',
    'Hatch speed is faster based on your tickspeed reduction multiplier.': '基于你的时间间隔降低倍率增幅孵化速度',
    'Hatch speed is faster based on your time shards.': '基于你的时间碎片数量增幅孵化速度',
    'How to play ': '游戏攻略',
    'I want the impossible challenge to be completed... I want to Big Rip the universe.': '我想完成不可能的挑战，我想撕裂这个宇宙',
    'If the multiplier per ten normal dimensions is 1x, then change it to': '如果每购买10个维度的加成倍率是1，则改变为',
    'Import': '导入',
    'Import preset': '导入设置',
    'Import spec': '导入专精',
    'Import tree': '导入永恒树',
    'Infinite Time reward is stronger in non-Dilation runs based on your Tachyon Particles.': '基于超光速粒子数量 无限时间奖励在非膨胀时间中会加强',
    'Infinity': '无限',
    'Infinity Challenge records': '无限挑战记录',
    'Infinity Dimensions': '无限维度',
    'Infinity dimensions gain a multiplier based on fastest eternity time': '基于最快到达永恒的时间增幅无限维度',
    'Infinity Dimensions multiplier based on sum of Infinity Challenge times': '基于所有无限挑战时间之和增幅无限维度',
    'Infinity Dimensions multiplier equal to unspent EP to the power of 5.': '无限维度增强未使用的永恒点数^5',
    'infinity power.': '无限力量',
    'Lead back to time studies.': '返回时间研究',
    'Load': '载入',
    'Lose a reset, returning to the start of the reset': '失去一个重置，返回重置之前',
    'Lose all your previous progress, but get a tickspeed boost': '失去所有进度，但是获得一个时间间隔的增幅',
    'Lose dimension boosts for better tickspeed multiplier': '失去维度提升获取更好的时间间隔倍率',
    'Main options': '主要选项',
    'Make the game 10% faster.': '使游戏快10%',
    'Make the IP formula better': '使无限点数获取使用更好的公式',
    'Mastery studies': '专精研究',
    'Max all': '购买所有',
    'Max all (M': '购买所有(M)',
    'Max all black hole dimensions': '购买所有黑洞维度',
    'Max all dilation upgrades': '购买所有膨胀时间研究',
    'Max all upgrades': '购买所有升级',
    'Max buy quantum food': '最大化购买量子食物',
    'Max EP mult': '购买最大永恒点增幅',
    'Max limit upgrades': '最大化升级',
    'Max replicanti galaxy upgrade cost is reduced based on replicanti amount.': '基于复制品的数量降低购买复制品星系上限需求的无限点数',
    'Meta Dimensions': '元维度',
    'Meta Dimensions are stronger based on your galaxies.': '基于星系数量增幅元维度',
    'Meta-antimatter effect on dimension boosts is stronger.': '基于维度提升增幅元维度',
    'meta-antimatter.': '元-反物质',
    'Meta-dimension boosts affect dilated time production.': '元维度提升会影响膨胀时间的产出',
    'Meta-dimension boosts are 4.5% stronger and cost scale by 1 less.': '元维度提升增强4.5%并且费用降低1',
    'Meta-dimension shifts, boosts, and per-ten upgrades are boosted by dilated time.': '基于膨胀时间提升元维度转换/提升/每10个元维度升级效率',
    'Mode: Amount of eternities': '模式：永恒的次数',
    'Multiplier per dimension boost': '增幅每一次维度提升的效率',
    'Multiplier to IP, decaying over this infinity': '增加无限点数的获取倍率，但是此次无限时间越久该加成越低',
    'Multiplier to IP, increasing over this infinity': '增加无限点数的获取倍率，并且此次无限时间越久该加成越高',
    'Normal dimension boost based on eternities': '基于永恒次数提升普通维度',
    'Normal dimensions gain a multiplier based on dilated time, unaffected by time dilation.': '',
    'Normal dimensions gain a multiplier based on time spent this eternity': '基于此次永恒进行的时间提升普通维度的效果',
    'normal replicants.': '普通复制品',
    'Options': '选项',
    'Other times await.. I need to become Eternal': '来不及解释了，我需要进行永恒',
    'Paired Challenge completions': '已完成的混合挑战',
    'Paradox': '悖论',
    'Paradox Dimensions': '悖论维度',
    'Paradox Power. Translated to': '悖论力量转化为',
    'Paradoxes.': '悖论次数',
    'Past Eternities': '过去的无限',
    'Past Ghostifies': '过去的幽灵化',
    'Past Infinities': '过去的无限',
    'Past Quantums': '过去的量子世界',
    'Pick all paths on all 3-way splits in time studies.': '同时选择时间研究的3条线路',
    'Pick all the study paths from the first split.': '同时选择时间研究的第一个分枝',
    'Pick all time studies before mastery studies.': '获取专精研究之前的所有时间研究',
    'Pick another path from the first split': '允许选择第一个分枝的另外一条线路',
    'Preon effect is 25% stronger.': '前子的效率增加25%',
    'Preons boost all Emperor Dimensions.': '前子增幅所有帝国维度',
    'Preons boost DT production at reduced rate.': '前子增幅膨胀时间的产出',
    'Quantum': '量子',
    'Quantum Challenge records': '量子挑战记录',
    'quantum food.': '量子食物',
    'red-green,': '红-绿',
    'Reduce the dilation penalty. (^ 1.05 after reduction': '提升膨胀时间时的产出^1.05',
    'Remote cost scaling starts 1 galaxy later per 3,000 dimension boosts.': '每拥有3000个维度提升，遥远反物质星系将延迟1个普通星系',
    'Remote cost scaling starts 1 galaxy later per 4.15 extra replicated galaxies.': '每拥有4.15个复制品星系，遥远反物质星系将延迟1个普通星系',
    'Remote cost scaling starts 1 galaxy later per 7 free galaxies.': '每拥有7个免费星系，遥远反物质星系将延迟1个普通星系',
    'Remote cost scaling starts 20 galaxies later per 9 extra replicated galaxies.': '每拥有9个额外复制品星系，遥远反物质星系将延迟20个普通星系',
    'Replicanti are 10x slower until infinity, but their galaxies are 50% stronger': '复制品的获取速度降低10倍，但是复制品星系增强50%',
    'Replicanti galaxies are 40% more effective': '复制品星系增强40%',
    'Replicanti galaxies power replicanti multiplier': '复制品星系将会增强复制品的增幅',
    'Replicanti increases faster based on dilated time.': '基于膨胀时间增幅复制品获取速度',
    'Replicanti interval limit 50ms ->': '复制品获取间隔峰值50ms→',
    'Replicanti multiplier': '复制品倍率',
    'Replicanti multiplier boosts DT production at greatly reduced rate.': '基于复制品膨胀时间获得极小的加强',
    'Replicanti multiplier boosts Meta Dimensions at greatly reduced rate.': '基于复制品元维度获得极小的加强',
    'Replicanti multiplier formula is better (log2(x)^2 -> x^': '复制品获取公式从(log2(x)^2 -> x^',
    'Replicanti multiplier to ID is 25% stronger': '复制品增幅无限维度力量增幅25%',
    'Replicanti multiplier to Infinity Dimensions is 17.3x stronger.': '复制品增幅无限维度增强17.3倍',
    'Replicantis give multiplier to normal dims equal to their amount.': '所有普通维度获得跟复制品数量一样数值的加成',
    'Replicate chance boosts itself.': '基于复制品概率增幅复制品概率',
    'Replicated galaxies are more effective based on your preons.': '基于前子数量增幅你的复制品星系效果',
    'Requirement: 1,300 Time upgrades gained from time dimensions': '需求1300个来源于时间维度的时间升级',
    'Requirement: 100,000,000 infinities': '需求100,000,000次无限次数',
    'Requirement: 1e100 EP': '需求1e100永恒点数',
    'Requirement: 1e550,000 antimatter': '需求1e550,000反物质',
    'Requirement: 1e6000 infinity power': '需求1e6000无限力量',
    'Requirement: 200 galaxies': '需求200个星系',
    'Requirement: 25,000 Eternities': '需求25,000次永恒',
    'Requirement: 40 replicanti galaxies': '需求40个复制品星系',
    'Requirement: 5 Eternity Challenge 11 and 12 completions': '需求永恒挑战11,12完成5次',
    'Requirement: Use only the Infinity Dimension path': '需求永恒树只使用无限维度加成分枝',
    'Requirement: Use only the Normal Dimension path': '需求永恒树只使用普通维度加成分枝',
    'RESET THE GAME': '重置游戏',
    'Reset the game for a new Dimension': '重置游戏以获得新的维度',
    'Respec mastery studies on next Eternity': '下次永恒时重置你的专精研究',
    'Respec time studies on next Eternity': '下次永恒时重置永恒树',
    'Sacrifice affects 3rd Time Dimension with greatly reduced effect': '维度献祭以极小的加成影响时间维度3',
    'Sacrifice affects 4th Infinity Dimension with greatly reduced effect': '维度献祭以极小的加成影响无尽维度4',
    'Sacrifice affects all other normal dimensions with reduced effect': '维度献祭以极小的加成影响所有其他普通维度',
    'Sacrifice affects the 4th Time Dimension with reduced effect.': '维度献祭以极小的加成影响时间维度4',
    'Sacrifice boosts First Dimension.': '维度献祭会影响维度1',
    'Sacrifice boosts the 8th dimension even more.': '维度献祭对维度8的加成效果更强',
    'Sacrifice is stronger (roughly 15% first time, total effect double-logarithmic in times bought': '维度献祭会更强,第一次大概强15%,总体大概会强献祭次数的双对数（total effect double-logarithmic in times bought）',
    'Sacrifice scales better.': '维度献祭的效果更强',
    'Save': '保存',
    'Saving': '存档',
    'Show ghostly news ticker': '显示幽灵化相关的新闻',
    'Show/hide stuff': '显示/隐藏功能',
    'Start a normal Eternity run.': '开始一轮普通的永恒',
    'Start eternities with 100% replicanti chance and 1 ms replicanti interval upgrades': '开始新的一轮永恒时保持100%的复制品复制概率以及1ms的复制品间隔',
    'Start Eternity Challenge 10.': '开启永恒挑战10',
    'Start with all normal dimensions available for purchase': '开始新的一轮时所有普通维度都可以直接购买',
    'Statistics': '统计',
    'Stop auto-dilate if a little bit of TP is gained: OFF': '暂停自动膨胀时间如果只获取了很少的超光速粒子（已关闭）',
    'Tachyon particles': '超光速粒子',
    'tachyon particles.': '超光速粒子',
    'The IP mult multiplies IP gain by 2.2x per upgrade.': '无限点获取增幅每次升级提升至2.2倍',
    'The production of preon anti-energy is slower based on your preons.': '基于你的前子数量前子反能量变得更加缓慢',
    'The production of preon energy is faster based on your replicants.': '基于你的复制品数量增幅前子能量',
    'The world has collapsed on itself due to excess of antimatter.\n ': '这个世界由于充满了反物质已经崩溃了.\n',
    'The worse your average EP/min is, the more EP you get': '你的平均永恒点/每分钟越低，获取的永恒点数越多',
    'Tickspeed': '时间间隔',
    'Tickspeed affects 1st Time Dimension with reduced effect': '时间间隔以极低的加成影响时间维度1',
    'Tickspeed boosts DT production at greatly reduced rate.': '时间间隔以极低的加成影响膨胀时间的产出',
    'Tickspeed boosts preon energy production.': '时间间隔以极低的加成影响前子能量的产出',
    'Time dilation': '时间膨胀',
    'Time Dimensions': '时间维度',
    'Time Dimensions are affected by replicanti multiplier ^ 0.1.': '基于复制品的^0.1加成给时间维度',
    'Time Dimensions are multiplied by days played': '基于游戏天数增幅时间维度',
    'Time Dimensions are multiplied by your unspent time theorems': '基于未使用的时间定理增幅时间维度',
    'Time dimensions gain a multiplier based on tick upgrades gained': '基于时间间隔升级增幅时间维度',
    'Time dimensions gain a multiplier equal to replicanti galaxy amount': '给予时间维度和复制品星系一样数量的加成倍数',
    'Time shard requirement for the next tickspeed upgrade goes up slower': '获取下一个时间间隔升级需求的时间碎片减少',
    'Time Shards boost all Meta Dimensions.': '基于时间碎片增幅所有元维度',
    'time shards. Next tickspeed upgrade at': '时间间隔，下一次升级时间间隔在',
    'Time studies': '时间研究',
    'Time Theorems': '时间定理',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '1 Eternity': '永恒1次',
    '2 Eternities': '永恒2次',
    '3 Eternities': '永恒3次',
    '4 Eternities': '永恒4次',
    '5 Eternities': '永恒5次',
    '7 Eternities': '永恒7次',
    '9 Eternities': '永恒9次',
    '10 Eternities': '永恒10次',
    '12 Eternities': '永恒12次',
    '13 Eternities': '永恒13次',
    '14 Eternities': '永恒14次',
    '15 Eternities': '永恒15次',
    '16 Eternities': '永恒16次',
    '17 Eternities': '永恒17次',
    '18 Eternities': '永恒18次',
    '20 Eternities': '永恒20次',
    '25 Eternities': '永恒25次',
    '30 Eternities': '永恒30次',
    '40 Eternities': '永恒40次',
    '50 Eternities': '永恒50次',
    '60 Eternities': '永恒60次',
    '80 Eternities': '永恒80次',
    '100 Eternities': '永恒100次',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',

    //原样
    '': '',
    '': '',

}


//需处理的前缀
var cnPrefix = {
    "(-": "(-",
    "(+": "(+",
    "(": "(",
    "-": "-",
    "+": "+",
    " ": " ",
    ": ": "： ",
}

//需处理的后缀
var cnPostfix = {
    ":": "：",
    "：": "：",
    ": ": "： ",
    "： ": "： ",
    " ": "",
    "/s)": "/s)",
    "/s": "/s",
    ")": ")",
    "%": "%",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^x?\d+(\.\d+)?[A-Za-z%]{0,2}(\s.C)?\s*$/, //12.34K,23.4 °C
    /^x?\d+(\.\d+)?(e[+\-]?\d+)?\s*$/, //12.34e+4
    /^\s*$/, //纯空格
    /^\d+(\.\d+)?[A-Za-z]{0,2}.?\(?([+\-]?(\d+(\.\d+)?[A-Za-z]{0,2})?)?$/, //12.34M (+34.34K
    /^(\d+(\.\d+)?[A-Za-z]{0,2}\/s)?.?\(?([+\-]?\d+(\.\d+)?[A-Za-z]{0,2})?\/s\stot$/, //2.74M/s (112.4K/s tot
    /^\d+(\.\d+)?(e[+\-]?\d+)?.?\(?([+\-]?(\d+(\.\d+)?(e[+\-]?\d+)?)?)?$/, //2.177e+6 (+4.01+4
    /^(\d+(\.\d+)?(e[+\-]?\d+)?\/s)?.?\(?([+\-]?(\d+(\.\d+)?(e[+\-]?\d+)?)?)?\/s\stot$/, //2.177e+6/s (+4.01+4/s tot
];
var cnExcludePostfix = [
    /:?\s*x?\d+(\.\d+)?(e[+\-]?\d+)?\s*$/, //12.34e+4
    /:?\s*x?\d+(\.\d+)?[A-Za-z]{0,2}$/, //: 12.34K, x1.5
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
var cnRegReplace = new Map([
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^(\d+) Royal points$/, '$1 皇家点数'],
    [/^Cost: (\d+) RP$/, '成本：$1 皇家点数'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);