/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],
    //未分类：
    '\n									Eighth Time Dimension': '\n									时间维度8',
    '\n									Fifth Time Dimension': '\n									时间维度5',
    '\n									First Time Dimension': '\n									时间维度1',
    '\n									Fourth Infinity Dimension': '\n									无尽维度4',
    '\n									Fourth Time Dimension': '\n									时间维度4',
    '\n									Second Time Dimension': '\n									时间维度2',
    '\n									Seventh Time Dimension': '\n									时间维度7',
    '\n									Sixth Time Dimension': '\n									时间维度6',
    '\n									Third Time Dimension': '\n									时间维度3',
    '\n								First Black Hole Dimension': '\n								黑洞维度1',
    '\n								Fourth Black Hole Dimension': '\n								黑洞维度4',
    '\n								Fourth Infinity Dimension': '\n								无尽维度4',
    '\n								Second Black Hole Dimension': '\n								黑洞维度2',
    '\n								Third Black Hole Dimension': '\n								黑洞维度3',
    '\n							  Eighth Meta Dimension\n						 ': '\n							  元维度8\n						 ',
    '\n							  Fifth Meta Dimension\n						 ': '\n							  元维度5\n						 ',
    '\n							  First Meta Dimension\n						 ': '\n							  元维度1\n						 ',
    '\n							  Fourth Meta Dimension\n						 ': '\n							  元维度4\n						 ',
    '\n							  Second Meta Dimension\n						 ': '\n							  元维度2\n						 ',
    '\n							  Seventh Meta Dimension\n						 ': '\n							  元维度7\n						 ',
    '\n							  Sixth Meta Dimension\n						 ': '\n							  元维度6\n						 ',
    '\n							  Third Meta Dimension\n						 ': '\n							  元维度3\n						 ',
    '\n							Amount of eternities to wait until dilate time': '\n							经过X次永恒自动开始膨胀时间',
    '\n							Antimatter Galaxies: requires 80 Eight Dimension\n						': '\n							反物质星系: 需求维度80个维度8\n						',
    '\n							Dimension Shift: requires 20 Fourth Dimension\n						': '\n							维度转换: 需求20个维度4\n						',
    '\n							First Infinity Dimension"': '\n							无尽维度1"',
    '\n							Fourth Infinity Dimension': '\n							无尽维度4',
    '\n							Second Infinity Dimension': '\n							无尽维度2',
    '\n							Third Infinity Dimension': '\n							无尽维度3',
    '\n							Tickspeed Boost (0): requires 10 Fifth Dimensions\n						': '\n							时间间隔加成 (0): 需求10个维度5\n						',
    '\n						  Meta-Dimension Shift: requires 20 Fourth Meta Dimensions\n					 ': '\n						  元维度变换: 需求20个元维度5\n					 ',
    '\n					You have': '\n					你拥有',
    '\n				Mastery study cost multiplier': '\n				专精研究花费倍率',
    '\n				Total TT spent to mastery studies': '\n				总共投入在专精研究上的时间定理',
    '\n				You have': '\n				你拥有',
    '1e11x multiplier on all Infinity Dimensions': '所有无尽维度增幅1e11倍',
    '1e4x multiplier on all Time Dimensions': '所有时间维度增幅1e4倍',
    '1e616x multiplier on all normal dimensions': '所有普通维度增幅1e616倍',
    'Achievements': '成就',
    'After eternity you permanently keep 5% of your infinities': '永恒后会保留5%的无限次数',
    'All replicated galaxies are stronger and use the same formula.': '所有复制品星系会更强并且拥有相同的公式.',
    'Animations': '动画',
    'antimatter.': '反物质.',
    'Auto-Eternity': '自动永恒',
    'Auto-save interval': '自动存档间隔',
    'Auto: ON': '自动已开启',
    'Automatic replicanti galaxies are disabled, but you can get 50% more': '你无法自动购买复制品星系，作为补偿你可以获得50%额外的复制品星系',
    'Automation': '自动化',
    'Big Crunch': '大坍塌',
    'Big Crunch for x Infinity Points': '大坍塌以获取X点无限点数',
    'Black hole': '黑洞',
    'black hole power. Translated to': '黑洞力量. 转化为',
    'Blue power boosts Meta Dimensions.': '蓝色力量可以增幅元维度.',
    'blue-red gluons.': '蓝-红 胶子.',
    'Boost first 4 Time Dimensions based on your Eternity Points and Eternal Matter.': '基于你的永恒点数以及永恒物质增幅前4个时间维度.',
    'Boost the ex-dilation gain.': '增幅EX-时间膨胀的获取.',
    'Boost tickspeed reduction based on your Eternity Points and Time Shards.': '基于永恒点和时间碎片增幅时间间隔.',
    'Boost Time Dimensions 4 - 6 based on your Eternity Points and Space Shards.': '基于永恒点和空间碎片增幅时间维度4~6.',
    'Break Eternity': '打破永恒',
    'BREAK ETERNITY': '打破永恒',
    'Break Eternity only works if you big rip the universe again.': '打破永恒只在你撕裂宇宙时生效.',
    'Buff the black hole upgrade effect based on your Eternity points.': '基于永恒点增幅你的黑洞升级.',
    'Buy all time studies': '购买所有时间研究',
    'Buy Max': '购买最大',
    'Cancel dilation penalty for Normal Dimensions boost from replicanti.': '取消膨胀时间对普通维度来源于复制品的惩罚.',
    'Challenge records': '挑战记录',
    'Challenges': '挑战',
    'Changelog  ': '更新日志  ',
    'Confirmations': '确认',
    'Cost': '费用',
    'Cost: 0 Time Theorems': '费用: 0 时间定理',
    'Cost: 1 Time Theorem': '费用: 1 时间定理',
    'Cost: 1,000,000 Time Theorems': '费用: 1,000,000 时间定理',
    'Cost: 1,000,000,000 Time Theorems': '费用: 1,000,000,000 时间定理',
    'Cost: 10 EP': '费用: 10 永恒点',
    'Cost: 10,000,000 Time Theorems': '费用: 10,000,000 时间定理',
    'Cost: 100 Time Theorems': '费用: 100 时间定理',
    'Cost: 100,000,000 Time Theorems': '费用: 100,000,000 时间定理',
    'Cost: 115 Time Theorems': '费用: 115 时间定理',
    'Cost: 12 Time Theorems': '费用: 12 时间定理',
    'Cost: 120 Time Theorems': '费用: 120 时间定理',
    'Cost: 15 Time Theorems': '费用: 15 时间定理',
    'Cost: 150 Time Theorems': '费用: 150 时间定理',
    'Cost: 1e12000 EP': '费用: 1e12000 永恒点',
    'Cost: 1e1500 EP': '费用: 1e1500 永恒点',
    'Cost: 1e16 EP': '费用: 1e16 永恒点',
    'Cost: 1e20 dilated time': '费用: 1e20 膨胀时间',
    'Cost: 1e2000 EP': '费用: 1e2000 永恒点',
    'Cost: 1e20000 EP': '费用: 1e20000 永恒点',
    'Cost: 1e3000 EP': '费用: 1e3000 永恒点',
    'Cost: 1e40 EP': '费用: 1e40 永恒点',
    'Cost: 1e4000 EP': '费用: 1e4000 永恒点',
    'Cost: 1e5 dilated time': '费用: 1e5 膨胀时间',
    'Cost: 1e50 EP': '费用: 1e50 永恒点',
    'Cost: 1e6 dilated time': '费用: 1e6 膨胀时间',
    'Cost: 1e7 dilated time': '费用: 1e7 膨胀时间',
    'Cost: 1e8 dilated time': '费用: 1e8 膨胀时间',
    'Cost: 1e8000 EP': '费用: 1e8000 永恒点',
    'Cost: 1e9 dilated time': '费用: 1e9 膨胀时间',
    'Cost: 2 Time Theorems': '费用: 2 时间定理',
    'Cost: 20 Time Theorems': '费用: 20 时间定理',
    'Cost: 200 Time Theorems': '费用: 200 时间定理',
    'Cost: 25 Time Theorems': '费用: 25 时间定理',
    'Cost: 3 Time Theorems': '费用: 3 时间定理',
    'Cost: 300 Time Theorems': '费用: 300 时间定理',
    'Cost: 4 Time Theorems': '费用: 4 时间定理',
    'Cost: 400 Time Theorems': '费用: 400 时间定理',
    'Cost: 5 EP': '费用: 5 永恒点',
    'Cost: 5 Time Theorems': '费用: 5 时间定理',
    'Cost: 50 K EP': '费用: 50000 永恒点',
    'Cost: 500 EP': '费用: 500 永恒点',
    'Cost: 500 Time Theorems': '费用: 500 时间定理',
    'Cost: 5000 Time Theorems': '费用: 5000 时间定理',
    'Cost: 5e6 dilated time': '费用: 5e6 膨胀时间',
    'Cost: 5e7 dilated time': '费用: 5e7 膨胀时间',
    'Cost: 6 Time Theorems': '费用: 6 时间定理',
    'Cost: 7 Time Theorems': '费用: 7 时间定理',
    'Cost: 730 Time Theorems': '费用: 730 时间定理',
    'Cost: 8 Time Theorems': '费用: 8 时间定理',
    'Cost: 85 Time Theorems': '费用: 85 时间定理',
    'Cost: 9 Time Theorems': '费用: 9 时间定理',
    'Cost: 900 Time Theorems': '费用: 900 时间定理',
    'Cost: xx banked infinities': '费用: xx 储存的无限次数',
    'Cost: xx dilated time': '费用: xx 膨胀时间',
    'Cost: xx replicanti': '费用: xx 复制品',
    'Current IP multiplier': '无限点数获取倍率',
    'Current tickspeed upgrades': '时间间隔升级次数',
    'Decrease the galaxy threshold multiplier, but resets free galaxies and dilated time.': '减少星系的门槛，但是重置免费星系和膨胀时间',
    'Dilate time.': '膨胀时间',
    'dilated time': '膨胀时间',
    'Dilated time gain is boosted by antimatter': '基于反物质数量增幅膨胀时间的获取',
    'Dilated time gain is boosted by eternity points': '基于永恒点数量增幅膨胀时间的获取',
    'Dilated time gain is boosted by infinity points': '基于无限点数量增幅膨胀时间的获取',
    'Dilated time production is boosted based on best meta-antimatter.': '基于最佳元-反物质数量增幅膨胀时间的获取',
    'dilated time, gained total of': '膨胀时间,总共免费星系个数',
    'Dilation options': '膨胀时间选项',
    'Dimension boost multiplier is incremented': '维度提升倍率是递增的',
    'Dimensional boost costs scale by another 1 less.': '维度提升费用降低1',
    'Dimensional boost costs scale by another 2 less.': '维度提升费用降低2',
    'Dimensional boost requirement scaling is reduced by': '维度提升费用降低',
    'Dimensional boosts affect Infinity Dimensions': '维度提升影响无限维度',
    'Dimensional boosts affect Meta Dimensions at reduced rate.': '维度提升以更低的效率影响元维度',
    'Dimensional boosts affect time dimensions with reduced power.': '维度提升以更低的效率影响时间维度',
    'Dimensional boosts are 0.04% more effective for each tick upgrade gained from Time Dimensions': '每拥有一个来源于时间维度的时间间隔升级维度提升提升0.04%的效率',
    'Dimensional boosts are more effective based on their amount.': '基于维度提升的次数维度提升将会更强',
    'Dimensional Sacrifice': '维度献祭',
    'Dimensions': '维度',
    'Disable hotkeys': '禁用快捷键',
    'Distribute ex-dilation': '分配EX-膨胀时间',
    'Divide normal galaxy cost in Eternity Challenge 10 based on your Eternal Matter.': '基于永恒物质的数量降低普通星系在永恒挑战10中的费用',
    'Divide the normal galaxy cost based on your Eternity Points.': '基于永恒点数降低普通星系的费用',
    'Double the dilated time production.': '膨胀时间产出*2',
    'Eighth Dimensions boost Meta Dimensions.': '维度8会增幅元维度',
    'Emperor Dimensions': '帝国维度',
    'Emperor Dimensions and hatch speed are faster by 25x.': '帝国维度以及孵化效率增幅25倍',
    'Enable': '启用',
    'enabled': '禁用',
    'Eternal Matter': '永恒物质',
    'Eternal Matter.': '永恒物质',
    'Eternities and dilated time boost each other by ^0.1.': '永恒次数与膨胀时间互相提升彼此效果 倍率^0.1',
    'Eternities and dilated time power up each other.': '永恒次数与膨胀时间互相提升彼此效果',
    'Eternity': '永恒',
    'Eternity Challenge': '永恒挑战',
    'Eternity Challenge records': '永恒挑战记录',
    'Eternity milestones': '永恒里程碑',
    'Eternity Points': '永恒点数',
    'Eternity upgrades': '永恒升级',
    'ex-dilation,': 'EX-膨胀时间',
    'Exponents of antimatter per second': '反物质每秒的指数',
    'Export': '导出',
    'Export "Infinite" bug save': '导出无限bug存档',
    'Export spec': '导出永恒专精',
    'Export tree': '导出永恒树',
    'extra seconds after matter exceeds your antimatter amount.': '正物质超过反物质的额外秒数',
    'Feed the black hole with banked infinities': '用储存的无尽次数填充黑洞',
    'Feed the black hole with dilated time': '用膨胀时间填充黑洞',
    'Feed the black hole with replicanti': '用复制品填充黑洞',
    'Free galaxies are as strong as a normal replicated galaxy.': '免费星系将会和普通复制品星系一样强',
    'free galaxy': '免费星系',
    'Gain 5% more Tachyon particles for each': '每个增加5%超光速粒子的获取',
    'Gain a multiplier to IP based on dilated time.': '基于膨胀时间获得无限点获取增幅',
    'Gain a multiplier to meta-dimensions based on tickspeed.': '基于时间间隔增幅元维度',
    'Gain twice as many free galaxies.': '获取双倍的免费星系',
    'Galaxies are more effective based on non-replicated galaxies.': '基于非复制品星系的数量增幅星系效果',
    'Galaxies are more effective based on your timeshards': '基于时间碎片的数量增幅星系效果',
    'Galaxy': '星系',
    'Galaxy cost scaling starts 1 galaxy later for every 2000 dimensional boosts.': '每拥有2000个维度提升 遥远星系将会延迟1个普通星系',
    'Galaxy cost scaling starts 7 galaxies later.': '遥远星系将会在额外7个普通星系之后',
    'Galaxy points.': '星系点',
    'Generate time theorems based on tachyon particles.': '基于超光速粒子的数量自动生成时间定理',
    'Get x antimatter to unlock a new Dimension.': '到达x个反物质解锁一个新的维度',
    'Ghost Particles.': '幽灵粒子',
    'Ghostify': '幽灵',
    'green-blue, and': '绿-蓝，和',
    'Hatch speed is faster based on your extra replicated galaxies.': '基于你的额外复制品星系数量增幅孵化速度',
    'Hatch speed is faster based on your meta-antimatter.': '基于你的元维度数量增幅孵化速度',
    'Hatch speed is faster based on your tachyon particles.': '基于你的超光速粒子数量增幅孵化速度',
    'Hatch speed is faster based on your tickspeed reduction multiplier.': '基于你的时间间隔降低倍率增幅孵化速度',
    'Hatch speed is faster based on your time shards.': '基于你的时间碎片数量增幅孵化速度',
    'How to play ': '游戏攻略',
    'I want the impossible challenge to be completed... I want to Big Rip the universe.': '我想完成不可能的挑战，我想撕裂这个宇宙',
    'If the multiplier per ten normal dimensions is 1x, then change it to': '如果每购买10个维度的加成倍率是1，则改变为',
    'Import': '导入',
    'Import preset': '导入设置',
    'Import spec': '导入专精',
    'Import tree': '导入永恒树',
    'Infinite Time reward is stronger in non-Dilation runs based on your Tachyon Particles.': '基于超光速粒子数量 无限时间奖励在非膨胀时间中会加强',
    'Infinity': '无限',
    'Infinity Challenge records': '无限挑战记录',
    'Infinity Dimensions': '无限维度',
    'Infinity dimensions gain a multiplier based on fastest eternity time': '基于最快到达永恒的时间增幅无限维度',
    'Infinity Dimensions multiplier based on sum of Infinity Challenge times': '基于所有无限挑战时间之和增幅无限维度',
    'Infinity Dimensions multiplier equal to unspent EP to the power of 5.': '无限维度增强未使用的永恒点数^5',
    'infinity power.': '无限力量.',
    'Lead back to time studies.': '返回时间研究',
    'Load': '载入',
    'Lose a reset, returning to the start of the reset': '失去一个重置，返回重置之前',
    'Lose all your previous progress, but get a tickspeed boost': '失去所有进度，但是获得一个时间间隔的增幅',
    'Lose dimension boosts for better tickspeed multiplier': '失去维度提升获取更好的时间间隔倍率',
    'Main options': '主要选项',
    'Make the game 10% faster.': '使游戏快10%',
    'Make the IP formula better': '使无限点数获取使用更好的公式',
    'Mastery studies': '专精研究',
    'Max all': '购买所有',
    'Max all (M': '购买所有(M)',
    'Max all black hole dimensions': '购买所有黑洞维度',
    'Max all dilation upgrades': '购买所有膨胀时间研究',
    'Max all upgrades': '购买所有升级',
    'Max buy quantum food': '最大化购买量子食物',
    'Max EP mult': '购买最大永恒点增幅',
    'Max limit upgrades': '最大化升级',
    'Max replicanti galaxy upgrade cost is reduced based on replicanti amount.': '基于复制品的数量降低购买复制品星系上限需求的无限点数',
    'Meta Dimensions': '元维度',
    'Meta Dimensions are stronger based on your galaxies.': '基于星系数量增幅元维度',
    'Meta-antimatter effect on dimension boosts is stronger.': '基于维度提升增幅元维度',
    'meta-antimatter.': '元-反物质',
    'Meta-dimension boosts affect dilated time production.': '元维度提升会影响膨胀时间的产出',
    'Meta-dimension boosts are 4.5% stronger and cost scale by 1 less.': '元维度提升增强4.5%并且费用降低1',
    'Meta-dimension shifts, boosts, and per-ten upgrades are boosted by dilated time.': '基于膨胀时间提升元维度转换/提升/每10个元维度升级效率',
    'Mode: Amount of eternities': '模式：永恒的次数',
    'Multiplier per dimension boost': '增幅每一次维度提升的效率',
    'Multiplier to IP, decaying over this infinity': '增加无限点数的获取倍率，但是此次无限时间越久该加成越低',
    'Multiplier to IP, increasing over this infinity': '增加无限点数的获取倍率，并且此次无限时间越久该加成越高',
    'Normal dimension boost based on eternities': '基于永恒次数提升普通维度',
    'Normal dimensions gain a multiplier based on dilated time, unaffected by time dilation.': '',
    'Normal dimensions gain a multiplier based on time spent this eternity': '基于此次永恒进行的时间提升普通维度的效果',
    'normal replicants.': '普通复制品',
    'Options': '选项',
    'Other times await.. I need to become Eternal': '来不及解释了，我需要进行永恒',
    'Paired Challenge completions': '已完成的混合挑战',
    'Paradox': '悖论',
    'Paradox Dimensions': '悖论维度',
    'Paradox Power. Translated to': '悖论力量转化为',
    'Paradoxes.': '悖论次数',
    'Past Eternities': '过去的无限',
    'Past Ghostifies': '过去的幽灵化',
    'Past Infinities': '过去的无限',
    'Past Quantums': '过去的量子世界',
    'Pick all paths on all 3-way splits in time studies.': '同时选择时间研究的3条线路',
    'Pick all the study paths from the first split.': '同时选择时间研究的第一个分枝',
    'Pick all time studies before mastery studies.': '获取专精研究之前的所有时间研究',
    'Pick another path from the first split': '允许选择第一个分枝的另外一条线路',
    'Preon effect is 25% stronger.': '前子的效率增加25%',
    'Preons boost all Emperor Dimensions.': '前子增幅所有帝国维度',
    'Preons boost DT production at reduced rate.': '前子增幅膨胀时间的产出',
    'Quantum': '量子',
    'Quantum Challenge records': '量子挑战记录',
    'quantum food.': '量子食物',
    'red-green,': '红-绿',
    'Reduce the dilation penalty. (^ 1.05 after reduction': '提升膨胀时间时的产出^1.05',
    'Remote cost scaling starts 1 galaxy later per 3,000 dimension boosts.': '每拥有3000个维度提升，遥远反物质星系将延迟1个普通星系',
    'Remote cost scaling starts 1 galaxy later per 4.15 extra replicated galaxies.': '每拥有4.15个复制品星系，遥远反物质星系将延迟1个普通星系',
    'Remote cost scaling starts 1 galaxy later per 7 free galaxies.': '每拥有7个免费星系，遥远反物质星系将延迟1个普通星系',
    'Remote cost scaling starts 20 galaxies later per 9 extra replicated galaxies.': '每拥有9个额外复制品星系，遥远反物质星系将延迟20个普通星系',
    'Replicanti are 10x slower until infinity, but their galaxies are 50% stronger': '复制品的获取速度降低10倍，但是复制品星系增强50%',
    'Replicanti galaxies are 40% more effective': '复制品星系增强40%',
    'Replicanti galaxies power replicanti multiplier': '复制品星系将会增强复制品的增幅',
    'Replicanti increases faster based on dilated time.': '基于膨胀时间增幅复制品获取速度',
    'Replicanti interval limit 50ms ->': '复制品获取间隔峰值50ms→',
    'Replicanti multiplier': '复制品倍率',
    'Replicanti multiplier boosts DT production at greatly reduced rate.': '基于复制品膨胀时间获得极小的加强',
    'Replicanti multiplier boosts Meta Dimensions at greatly reduced rate.': '基于复制品元维度获得极小的加强',
    'Replicanti multiplier formula is better (log2(x)^2 -> x^': '复制品获取公式从(log2(x)^2 -> x^',
    'Replicanti multiplier to ID is 25% stronger': '复制品增幅无限维度力量增幅25%',
    'Replicanti multiplier to Infinity Dimensions is 17.3x stronger.': '复制品增幅无限维度增强17.3倍',
    'Replicantis give multiplier to normal dims equal to their amount.': '所有普通维度获得跟复制品数量一样数值的加成',
    'Replicate chance boosts itself.': '基于复制品概率增幅复制品概率',
    'Replicated galaxies are more effective based on your preons.': '基于前子数量增幅你的复制品星系效果',
    'Requirement: 1,300 Time upgrades gained from time dimensions': '需求1300个来源于时间维度的时间升级',
    'Requirement: 100,000,000 infinities': '需求100,000,000次无限次数',
    'Requirement: 1e100 EP': '需求1e100永恒点数',
    'Requirement: 1e550,000 antimatter': '需求1e550,000反物质',
    'Requirement: 1e6000 infinity power': '需求1e6000无限力量',
    'Requirement: 200 galaxies': '需求200个星系',
    'Requirement: 25,000 Eternities': '需求25,000次永恒',
    'Requirement: 40 replicanti galaxies': '需求40个复制品星系',
    'Requirement: 5 Eternity Challenge 11 and 12 completions': '需求永恒挑战11,12完成5次',
    'Requirement: Use only the Infinity Dimension path': '需求永恒树只使用无限维度加成分枝',
    'Requirement: Use only the Normal Dimension path': '需求永恒树只使用普通维度加成分枝',
    'RESET THE GAME': '重置游戏',
    'Reset the game for a new Dimension': '重置游戏以获得新的维度',
    'Respec mastery studies on next Eternity': '下次永恒时重置你的专精研究',
    'Respec time studies on next Eternity': '下次永恒时重置永恒树',
    'Sacrifice affects 3rd Time Dimension with greatly reduced effect': '维度献祭以极小的加成影响时间维度3',
    'Sacrifice affects 4th Infinity Dimension with greatly reduced effect': '维度献祭以极小的加成影响无尽维度4',
    'Sacrifice affects all other normal dimensions with reduced effect': '维度献祭以极小的加成影响所有其他普通维度',
    'Sacrifice affects the 4th Time Dimension with reduced effect.': '维度献祭以极小的加成影响时间维度4',
    'Sacrifice boosts First Dimension.': '维度献祭会影响维度1',
    'Sacrifice boosts the 8th dimension even more.': '维度献祭对维度8的加成效果更强',
    'Sacrifice is stronger (roughly 15% first time, total effect double-logarithmic in times bought': '维度献祭会更强,第一次大概强15%,总体大概会强献祭次数的双对数（total effect double-logarithmic in times bought）',
    'Sacrifice scales better.': '维度献祭的效果更强',
    'Save': '保存',
    'Saving': '存档',
    'Show ghostly news ticker': '显示幽灵化相关的新闻',
    'Show/hide stuff': '显示/隐藏功能',
    'Start a normal Eternity run.': '开始一轮普通的永恒',
    'Start eternities with 100% replicanti chance and 1 ms replicanti interval upgrades': '开始新的一轮永恒时保持100%的复制品复制概率以及1ms的复制品间隔',
    'Start Eternity Challenge 10.': '开启永恒挑战10',
    'Start with all normal dimensions available for purchase': '开始新的一轮时所有普通维度都可以直接购买',
    'Statistics': '统计',
    'Stop auto-dilate if a little bit of TP is gained: OFF': '暂停自动膨胀时间如果只获取了很少的超光速粒子（已关闭）',
    'Tachyon particles': '超光速粒子',
    'tachyon particles.': '超光速粒子',
    'The IP mult multiplies IP gain by 2.2x per upgrade.': '无限点获取增幅每次升级提升至2.2倍',
    'The production of preon anti-energy is slower based on your preons.': '基于你的前子数量前子反能量变得更加缓慢',
    'The production of preon energy is faster based on your replicants.': '基于你的复制品数量增幅前子能量',
    'The world has collapsed on itself due to excess of antimatter.\n ': '这个世界由于充满了反物质已经崩溃了.\n',
    'The worse your average EP/min is, the more EP you get': '你的平均永恒点/每分钟越低，获取的永恒点数越多',
    'Tickspeed': '时间间隔',
    'Tickspeed affects 1st Time Dimension with reduced effect': '时间间隔以极低的加成影响时间维度1',
    'Tickspeed boosts DT production at greatly reduced rate.': '时间间隔以极低的加成影响膨胀时间的产出',
    'Tickspeed boosts preon energy production.': '时间间隔以极低的加成影响前子能量的产出',
    'Time dilation': '时间膨胀',
    'Time Dimensions': '时间维度',
    'Time Dimensions are affected by replicanti multiplier ^ 0.1.': '基于复制品的^0.1加成给时间维度',
    'Time Dimensions are multiplied by days played': '基于游戏天数增幅时间维度',
    'Time Dimensions are multiplied by your unspent time theorems': '基于未使用的时间定理增幅时间维度',
    'Time dimensions gain a multiplier based on tick upgrades gained': '基于时间间隔升级增幅时间维度',
    'Time dimensions gain a multiplier equal to replicanti galaxy amount': '给予时间维度和复制品星系一样数量的加成倍数',
    'Time shard requirement for the next tickspeed upgrade goes up slower': '获取下一个时间间隔升级需求的时间碎片减少',
    'Time Shards boost all Meta Dimensions.': '基于时间碎片增幅所有元维度',
    'time shards. Next tickspeed upgrade at': '时间碎片，下一次升级时间间隔在',
    'Time studies': '时间研究',
    'Time Theorems': '时间定理',
    '1 Eternity': '永恒1次',
    '2 Eternities': '永恒2次',
    '3 Eternities': '永恒3次',
    '4 Eternities': '永恒4次',
    '5 Eternities': '永恒5次',
    '7 Eternities': '永恒7次',
    '9 Eternities': '永恒9次',
    '10 Eternities': '永恒10次',
    '12 Eternities': '永恒12次',
    '13 Eternities': '永恒13次',
    '14 Eternities': '永恒14次',
    '15 Eternities': '永恒15次',
    '16 Eternities': '永恒16次',
    '17 Eternities': '永恒17次',
    '18 Eternities': '永恒18次',
    '20 Eternities': '永恒20次',
    '25 Eternities': '永恒25次',
    '30 Eternities': '永恒30次',
    '40 Eternities': '永恒40次',
    '50 Eternities': '永恒50次',
    '60 Eternities': '永恒60次',
    '80 Eternities': '永恒80次',
    '100 Eternities': '永恒100次',
    'Auto crunch mode: amount': '自动大坍塌模式：点数到达数量',
    'Auto eternity mode: amount': '自动永恒模式：点数到达数量',
    'Auto galaxy OFF': '自动购买星系关闭',
    'Autobuyers': '自动化',
    'Autobuyers work twice as fast': '自动化效率翻倍',
    'Automated Galaxies': '自动购买星系',
    'Automatic Big Crunch': '自动大坍塌',
    'Automatic DimBoosts': '自动维度提升',
    'Automatic Eternity': '自动永恒',
    'Automatic Galactic Sacrifice': '自动星系献祭',
    'Automatic Quantum': '自动进入量子世界',
    'Automatic Sacrifice': '自动维度献祭',
    'Automatic Tickspeed Boosts': '自动购买时间间隔',
    'Automatic Time Dimension Boosts': '自动购买时间维度提升',
    'Big Rip': '撕裂宇宙',
    'Break Infinity': '打破无尽',
    'BREAK INFINITY': '打破无尽',
    'Bulk DimBoost amount': '批量维度提升数量',
    'Bulk Tickspeed Boost amount': '批量时间间隔提升数量',
    'Buy max galaxies every X seconds (0 to always buy': '每x秒购买最大星系（0秒则一直购买',
    'Buying a dimension automatically erases all lower tier dimensions, like a sacrifice without the boost.': '就像维度献祭一样,购买任意维度都会清除所有比它低等级的维度然而无献祭的加成',
    'Buying anything halts your production, gradually coming back over 3 minutes.': '购买任何东西都会停止所有维度的生产,3分钟内逐渐恢复正常',
    'Buys singles': '购买单个',
    'Complete Eternity Challenges again for a bigger reward, maximum of 5 times.': '再次完成永恒挑战获得更高的奖励,永恒挑战最多可以完成5次',
    'Completed 0 Times.': '已完成0次',
    'Cost: ??? GP': '费用: ???星系点数',
    'Cost: 1 Qa IP': '费用: 1Qa无限点数',
    'Cost: 10 K IP': '费用: 10K无限点数',
    'Cost: 10 M IP': '费用: 1M无限点数',
    'Cost: 100 GP': '费用: 100星系点数',
    'Cost: 100 IP': '费用: 100无限点数',
    'Cost: 100 K IP': '费用: 100K无限点数',
    'Cost: 1e140 IP': '费用: 1e140无限点数',
    'Cost: 1e2000 IP': '费用: 1e2000无限点数',
    'Cost: 1e25 IP': '费用: 1e25无限点数',
    'Cost: 1e29 IP': '费用: 1e29无限点数',
    'Cost: 1e33 IP': '费用: 1e33无限点数',
    'Cost: 1e37 IP': '费用: 1e37无限点数',
    'Cost: 1e450 IP': '费用: 1e450无限点数',
    'Cost: 1e50 IP': '费用: 1e50无限点数',
    'Cost: 1e700 IP': '费用: 1e700无限点数',
    'Cost: 1e95 IP': '费用: 1e95无限点数',
    'Cost: 2 points': '费用: 2点',
    'Cost: 20 M IP': '费用: 20M无限点数',
    'Cost: 3 M IP': '费用: 3M无限点数',
    'Cost: 300 GP': '费用: 300星系点数',
    'Cost: 300 K IP': '费用: 300K无限点数',
    'Cost: 5 GP': '费用: 5星系点数',
    'Cost: 50 K IP': '费用: 5K无限点数',
    'Cost: 500 K IP': '费用: 500K无限点数',
    'Current achievement multiplier on each Dimension': '基于成就完成行数对所有维度提升的倍率',
    'Current interval: 0.10 seconds': '当前间隔：0.1s',
    'Current interval: 30 seconds': '当前间隔：30s',
    'Current interval: 5 seconds': '当前间隔：5s',
    'Current interval: 60 seconds': '当前间隔：60s',
    'currently': '目前',
    'Currently': '目前',
    'Currently: /': '目前: /',
    'Currently: ^': '目前: ^',
    'Currently: +': '目前: +',
    'Currently: x': '目前: x',
    'Currently: x^': '目前: x^',
    'Currently: Xx': '目前: Xx',
    'dark matter per second.': '每秒黑暗物质',
    'dark matter. Translated to': '黑暗物质,转化为',
    'Decrease tickspeed boost cost multiplier to 4.': '降低时间间隔升级价格倍增至4',
    'Dilated time boost Seventh Time Dimension.': '基于膨胀时间增幅时间维度7',
    'Dimension boost cost increases by 0.5 less.': '维度提升的费用降低0.5',
    'Dimension boost multipliers of Normal Dimensions and Infinity Dimensions are disabled.': '维度提升对普通维度和无限维度无加成',
    'Dimension Boosts and galaxies are useless, sacrifice resets everything but is immensely more powerful.': '维度提升和星系无任何加成,作为维度献祭将会获得极大的增幅',
    'Dimension boosts are disabled.': '你无法使用维度提升',
    'Dimension Boosts make g13 stronger.': '维度提升使g13更强',
    'Dimension cost multiplier increase': '升级维度的价格变高了',
    'Dimensions 5-8 don\'t produce anything. Dimensional sacrifice is disabled.': '维度5~8不产生任何东西且你无法使用维度献祭',
    'Disable bulk buy': '禁用批量购买',
    'Divide all Infinity Dimension cost multipliers by 50.': '无限维度的升级价格/50',
    'Don\'t auto-respec studies and auto-reunlock ECs': '自动解锁永恒挑战且不重置永恒树',
    'Double the power of Galaxies': '星系的效果翻倍',
    'Each dimension costs the dimension 2 before it, with modified prices': '每个维度都要花费低2级的维度,并且修改了价格',
    'Each replicated galaxy increases your EP gain by 2x.': '每个复制品星系增加永恒点获取倍率2倍',
    'Enable/disable autobuyers': '启用/禁用自动化',
    'Eternity Challenges': '永恒挑战',
    'Eternity points reduce Infinity Dimension cost multipliers.': '基于永恒点数降低无限维度价格倍率',
    'Eternity Points start Distant Antimatter Galaxies scaling later.': '遥远反物质星系会基于永恒点的数量来的更晚一些',
    'Exit Challenge': '退出挑战',
    'First dimension is heavily weakened but gets an exponentially increasing bonus that resets on reset.': '第一维度效果极度削弱,作为补偿会获得一个指数型的增长,游戏重置时也会重置该效果',
    'First Time Dimension produces Eighth Infinity Dimension, and First Infinity Dimension produces Seventh Dimensions. Tickspeed affects all dimensions normally.': '时间维度1会生产无限维度8,无限维度1会生成普通维度7,时间间隔升级影响所有维度',
    'For next eternity': '下一次永恒',
    'g11 formula is better.': 'g11的公式将会更加好',
    'Gain 1,350 Time Theorems but reset the study tree and repeal upgrades 3 & 5 - 8.': '获得1350个时间定理，但是将重置你的永恒树并且废除3 & 5 - 8升级',
    'Gain 20 Time Theorems.': '获得20个时间定理',
    'Gain 5 Time Theorems.': '获得5个时间定理',
    'Gain more galaxy points based on your total antimatter.': '基于反物质数量获得更多的星系点数',
    'Galaxies are 20% more stronger.': '星系增强20%',
    'Galaxies have no effect.': '星系没有任何效果',
    'Galaxy bulk mode: single': '星系购买模式：单个',
    'Galaxy cost increase scaling starts instantly (Normally at 100 galaxies). Dimension boost costs scaling is massively increased.': '遥远反物质星系会立即开始（原本是从100个开始）,并且维度提升的价格增长了很多',
    'Galaxy cost increases by 3 less.': '星系的费用增加了3',
    'Goal': '目标',
    'Goal: 1e1000 IP': '目标: 1e1000无限点数',
    'Goal: 1e110000 in 0.5 seconds or less.': '目标:在0.5秒内到达1e110000无限点数',
    'Goal: 1e2000 IP': '目标: 1e2000无限点数',
    'Goal: 1e2700 IP': '目标: 1e2700无限点数',
    'Goal: 1e3000 IP': '目标: 1e3000无限点数',
    'Goal: 1e400 IP': '目标: 1e400无限点数',
    'Goal: 1e4250 IP in 20 infinities': '目标:在无限不超过20次的情况下到达1e4250无限点数',
    'Goal: 1e750 IP': '目标: 1e750无限点数',
    'GP': '星系点数',
    'IC2, IC6, IC7, and IC8 are applied to Normal, Infinity and Time Dimensions, and IC3 is applied to Normal Dimensions. Matter cannot surpass antimatter or you fail the challenge, and you can\'t gain dimension boosts. However, the multiplier per ten meta dimensions is a little bit stronger.': '无限挑战2/6/7/8的效果现在同样作用于普通/无限/时间维度,无限挑战3的效果同样作用于普通维度,正物质数量不能超过反物质数量否则你将挑战失败,你无法获得维度提升,作为补偿每购买10次维度的加成会变得更强一点',
    'Increase all dimension multipliers.': '增加所有维度的倍率',
    'Increase the limit of Infinity.': '增加无限的限制',
    'Increase the multiplier of the product of bought based on your galaxy points.': '基于星系点增加产出',
    'Increase the production of all dimensions based on slowest challenge run': '基于最快的挑战时间增加所有维度的产出',
    'Increase the production of all dimensions by amount infinitied': '基于无限次数增加所有维度的产出',
    'Infinity Challenges': '无限挑战',
    'Infinity Dimensions are disabled.': '你无法购买无限维度',
    'Infinity Dimensions can only be boosted by meta-antimatter. Meta-antimatter never boosts dimension boosts.': '无限维度现在只会增强元维度,且元维度不会增幅维度提升',
    'Infinity Dimensions, Time Dimensions, and Meta-Dimension Boosts are disabled.': '无限维度/时间维度/元维度都被禁用了',
    'Infinity points.\n ': '无限点数.\n',
    'IP': '无限点数',
    'Is active': '勾选以激活',
    'Level': '等级',
    'Make the first upgrade active again but 2.9x stronger.': '使第一个升级再次激活且增幅2.9倍',
    'Max 8ths used on reset': '重置时允许使用的维度8最大数量',
    'Max Galaxies': '允许的最大星系数量',
    'Max Replicanti galaxies': '最大复制品星系数量',
    'Multiplier per 10 dimensions is random from 0.30 and': '每10次购买维度提升倍率随机从0.3到',
    'Multiplier per ten dimensions and dimension boost power are always 1x and tickspeed boost effect softcap starts immediately.': '每购买10个维度以及维度提升的效果变为1倍且时间间隔升级立刻影响softcap开始',
    'Multiplier per ten dimensions is stronger based on your galaxy points.': '基于星系点数增幅每10次购买维度的增幅',
    'Multiply infinity points from all sources by': '基于所有资源提升总共获得的无限点获取倍率',
    'Normal Dimensions 3-8 don\'t produce anything. You don\'t lose everything when you buy Normal Dimensions or tickspeed.': '普通维度3~8不再产生任何东西，但是你购买普通维度或时间间隔时不会再失去所有',
    'Option to bulk buy Dimension Boosts': '批量购买维度增幅',
    'Powers up bonuses that are based on your infinitied stat (to the power of': '增幅了基于无限次数的加成项目(至^',
    'Preset automation': '自动化预设',
    'Priority': '优先级',
    'Production': '生产',
    'Quantum Challenges': '量子挑战',
    'Quantumed': '量子次数',
    'Translated to': '转化为',
    'replicanti. Translated to': '复制品,转化为',
    'Replicantis': '复制品',
    'Replicantis boost Time Dimensions at greatly reduced rate.': '时间维度基于复制品数量获得极小的加成',
    'Replicantis multiply the gain of Infinity Points (at reduced rate) and replicate speed is 10x faster.': '基于复制品数量略微增加无限点数的获取倍率,且复制品速度增加10%',
    'Replicate chance': '复制成功率',
    'Require max replicanti': '需要最大复制品',
    'Reset replicanti amount, but get a free galaxy': '重置复制品以获得一个免费星系',
    'Respec paired challenges on next': '下次重置混合挑战',
    'Respec paired challenges on next quantum': '下次进入量子世界时重置混合挑战',
    'Reward: All normal dimension multipliers become multiplier^': '奖励:所有普通维度的倍增变为^',
    'Reward: Automated Big Crunches': '奖励: 大坍塌自动化',
    'Reward: Automated Dimension Boosts': '奖励: 维度提升自动化',
    'Reward: Automated Dimensional Sacrifice': '奖励: 维度献祭自动化',
    'Reward: Automated Galactic Sacrifice': '奖励: 星系献祭自动化',
    'Reward: Automated Galaxies': '奖励: 星系自动化',
    'Reward: Automated Tickspeed Boosts': '奖励: 时间间隔自动化',
    'Reward: Automated Time Dimension Boosts': '奖励: 时间维度提升自动化',
    'Reward: Cost multiplier increases are x^.9, and tickspeed cost multiplier increase is further lowered based on galaxies.': '奖励: 费用倍率降低至^0.9,并且基于星系数量降低时间间隔升级的价格',
    'Reward: Dimension & tickspeed boosts also boost infinity power.': '奖励: 维度和时间间隔增幅也会影响无限力量',
    'Reward: dunno': '奖励: ???',
    'Reward: Eighth Dimension autobuyer': '奖励: 维度8自动化',
    'Reward: Every tickspeed purchase decreases tickspeed based on galaxies': '奖励: 基于星系数量每次购买时间间隔会提升额外时间间隔',
    'Reward: Fifth Dimension autobuyer': '奖励: 维度5自动化',
    'Reward: First Dimension autobuyer': '奖励: 维度1自动化',
    'Reward: Fourth Dimension autobuyer': '奖励: 维度4自动化',
    'Reward: Further reduction dimension cost multiplier increase, Current': '奖励: 进一步降低维度升级的价格倍增,当前为',
    'Reward: Galaxies are 10% more powerful and reduce the requirements for them and dimensional boosts by': '奖励:星系效果增强10%,且星系和维度提升需求减少',
    'Reward: Galaxy cost scaling starts 10 galaxies later': '奖励: 遥远星系会晚10个星系到来',
    'Reward: Galaxy exponent boost to Galaxy points gain is buffed.': '奖励: 星系点数基于星系数量获得指数提升',
    'Reward: Galaxy points boost Tickspeed Boosts.': '奖励: 基于星系点数获得时间间隔增强',
    'Reward: idk lol': '奖励: 我也不知道哈哈哈哈',
    'Reward: Infinity Dimension cost multipliers are reduced. (x^': '奖励: 无限维度价格降低^',
    'Reward: Infinity Dimension multiplier based on time shards, Current': '奖励:基于时间碎片增加无限维度的倍率,当前',
    'Reward: Infinity Dimension multiplier from unspent IP': '奖励: 基于未使用的无限点数增幅无限维度的倍率',
    'Reward: Sacrifice autobuyer and more powerful sacrifice': '奖励: 维度献祭自动化,以及提升维度献祭的效率',
    'Reward: Second Dimension autobuyer': '奖励: 维度2自动化',
    'Reward: Seventh Dimension autobuyer': '奖励: 维度7自动化',
    'Reward: Sixth Dimension autobuyer': '奖励: 维度6自动化',
    'Reward: something good I hope': '奖励: 我希望是一些很给力的东西',
    'Reward: Static multiplier on each tickspeed purchase': '奖励: 静态增加每次购买时间间隔的增幅',
    'Reward: Third Dimension autobuyer': '奖励: 维度3自动化',
    'Reward: Tickspeed affects Infinity Dimensions with reduced effect': '奖励: 基于时间价格获得小幅度的无限维度加成',
    'Reward: Tickspeed autobuyer': '奖励: 时间间隔自动化',
    'Reward: Xx on all Time Dimensions (based on time spent this Eternity': '奖励: 基于此次永恒花费的时间增幅所有时间维度',
    'Reward: You get a multiplier to dimensions 2-7 based on 1st and 8th dimension multipliers.': '奖励: 基于维度1和维度8的倍率对维度2~7进行倍率加成',
    'Sacrifice all of your infinity points, but gain': '献祭你所有无限点数以获得',
    'Sacrifice is stronger.': '献祭会变得更强',
    'Sacrifice when the multiplier is over': '当倍率超过x时献祭',
    'Secret Achievements': '隐藏成就',
    'Singularity': '奇点',
    'singularity power.': '奇点力量',
    'Space Shards': '空间碎片',
    'Space Shards boost Eternity Points gain.': '基于空间碎片获得永恒点数增幅',
    'Space Shards.\n ': '空间碎片\n',
    'Special preset automation': '特别的自动化预设',
    'Spend electrons to start quantum challenges.': '花费电子开始一个量子挑战',
    'Start': '开始',
    'Start with all ECs completed and 100,000 eternities.': '开始游戏时已完成所有永恒挑战,并且拥有100,000次永恒次数',
    'Start with dilation unlocked, but activates 9th Big Rip upgrade.': '开始时已拥有膨胀时间,但是激活了撕裂宇宙第9个升级',
    'Start with Tachyon particles but reset the study tree, all upgrades can boost dilation except your best TP, and repeal all others.': '开始时拥有超光速粒子,但是重置永恒树,除了历史最佳超光速粒子其他升级都会增幅膨胀时间,并且废除了其他的加成',
    'The game runs 1000x slower.': '游戏速度降低1000倍',
    'The world has collapsed on itself due to excess of antimatter.\n ': '世界由于充满了反物质崩溃了.\n',
    'There\'s an exponentially rising matter that divides the multiplier on all of your dimensions.': '所有维度的产出除以一个指数增长的正物质',
    'There\'s normal matter which rises. If it exceeds your antimatter, it will dimension boost without giving the bonus.': '正物质不断增长,如果超过了反物质则会重置所有维度并且无加成',
    'Tickspeed Autobuyer': '时间间隔自动化',
    'Tickspeed Autobuyer Challenge, Automated Big Crunches Challenge, Automated Galacitc Sacrifice Challenge, and Automated Tickspeed Boosts Challenge at once.': '同时进行时间间隔/大坍塌/星系献祭/时间间隔增幅4个自动化挑战',
    'Tickspeed interval decrease is always at 0%, but every tickspeed purchase you get a static multiplier on all dimensions (increases with galaxies).': '时间间隔增长总是0%,但是每次购买时间间隔会获得一个静态的加成给所有维度(该加成受星系影响)',
    'Tickspeed Multiplier boost to Time Dimensions is weaker.': '时间间隔对时间维度的影响更弱',
    'Tickspeed multiplier boosts Time Dimensions more based on your Galaxy points.': '基于星系点数时间间隔增幅时间维度',
    'Time Dimensions and Infinity Dimensions are disabled, You gain an immense boost from infinitied stat to normal dimensions': '时间维度和无限维度被禁用,但是基于无限次数你会获得一个巨大的加成给所有普通维度',
    'Time Dimensions are disabled.': '时间维度已禁用',
    'Toggle all meta-dims autobuyer ON/OFF': '启用所有元维度自动化ON/OFF',
    'Toggle all ON/OFF': '启用所有ON/OFF',
    'Total': '总共',
    'Total sacrifice multiplier': '总共献祭倍率',
    'TS101 is stronger based on your Space Shards but doesn\'t work on dilation.': '基于你的空间碎片,时间研究101效果更强但是在膨胀时间中无效',
    'TT': '时间定理',
    'Unlock 2 new rows of Galaxy Points.': '解锁2行新的星系点数项',
    'Unlock a secret achievement': '解锁一个隐藏成就',
    'Unlock autobuy max Dimensional Boosts': '解锁最大维度提升',
    'Unlock autobuy max galaxies': '解了购买最大星系',
    'Unlock autobuyer for Eighth Infinity Dimension': '解锁无限维度8自动化',
    'Unlock autobuyer for Eternities': '解锁自动永恒',
    'Unlock autobuyer for Fifth Infinity Dimension': '解锁无限维度5自动化',
    'Unlock autobuyer for First Infinity Dimension': '解锁无限维度1自动化',
    'Unlock autobuyer for Fourth Infinity Dimension': '解锁无限维度4自动化',
    'Unlock autobuyer for replicanti chance upgrade': '解锁复制品概率升级自动化',
    'Unlock autobuyer for replicanti galaxy upgrade': '解锁最大复制品星系自动化',
    'Unlock autobuyer for replicanti interval upgrade': '解锁复制品间隔自动化',
    'Unlock autobuyer for Second Infinity Dimension': '解锁无限维度2自动化',
    'Unlock autobuyer for Seventh Infinity Dimension': '解锁无限维度7自动化',
    'Unlock autobuyer for Sixth Infinity Dimension': '解锁无限维度6自动化',
    'Unlock autobuyer for Third Infinity Dimension': '解锁无限维度3自动化',
    'Unlock Big Rip': '解锁撕裂宇宙',
    'Unlock Electrons': '解锁电子',
    'Unlock Emperor Dimensions': '解锁帝国维度',
    'Unlock IP multiplier autobuyer': '解锁无限点数翻倍自动化',
    'Unlock Meta Dimensions': '解锁元维度',
    'Unlock more big crunch autobuyer options.': '解锁更多的大坍塌自动化设定',
    'Unlock Nanofield': '解锁纳米领域',
    'Unlock Paired Challenges': '解锁混合挑战',
    'Unlock Quantum Challenges': '解锁量子挑战',
    'Unlock replicanti amount mode for eternity autobuyer': '解锁根据复制品数量进行自动永恒',
    'Unlock replicanti galaxy autobuyer': '解锁复制品星系总动画',
    'Unlock Replicantis': '解锁复制品',
    'Unlock Replicants': '解锁复制品',
    'Unlock Singularity': '解锁奇点',
    'Unlock the 5th Time Dimension': '解锁时间维度5',
    'Unlock the 6th Time Dimension': '解锁时间维度6',
    'Unlock the 7th Time Dimension': '解锁时间维度7',
    'Unlock the 8th Time Dimension': '解锁时间维度8',
    'Unlock the black hole': '解锁黑洞',
    'Unlock time dilation': '解锁时间膨胀',
    'Unlock time since peak changed mode for eternity autobuyer': '解锁离开最佳EP获取多少秒之后自动永恒',
    'Unlock Tree of Decay': '解锁衰变之树',
    'Update Rate': '刷新速率',
    'update rate (in ms': '刷新速度(毫秒',
    'When you dimension boost, you keep your antimatter and dimensions': '当你进行维度提升时将会保留反物质和维度',
    'Workers boost Meta Dimensions.': '工人会增幅元维度',
    'x faster tickspeed.': 'x倍时间间隔',
    'x more Eternity Points.': 'x倍永恒点',
    'x more power': 'x倍力量',
    'x multiplier on all dimensions': 'x倍普通维度加成',
    'x multiplier on all infinity dimensions': 'x倍无限维度加成',
    'x multiplier on banked infinity gain and replicanti speed': 'x倍储存无限次数获取以及复制品复制速率',
    'x multiplier on dilated time gain and': 'x倍膨胀时间获取和',
    'You are getting 0 antimatter per second.': '你每秒获得0个反物质',
    'You are getting 0 black hole power per second.': '你每秒获得0黑洞力量',
    'You are getting 0 meta-antimatter per second.': '你每秒获得0元-反物质',
    'You are getting 0 Paradox Power per second.': '你每秒获得0悖论力量',
    'You are getting 0 Timeshards per second.': '你每秒获得0时间碎片',
    'You automatically unlock Infinity Dimensions upon reaching them': '当你的反物质超过无限维度的阈值时自动激活无限维度',
    'You can buy beyond 1ms interval upgrades but the cost starts to increase faster.': '你可以将间隔购买到1ms以下,但是之后的价格增长更快',
    'You can buy replicate chance upgrades over 100%.': '你可以升级复制概率超过100%',
    'You can gain tachyon particles without disabling dilation.': '即使不进行时间膨胀也可以获得超光速粒子',
    'You can get beyond 1.8e308 replicantis, but the interval is increased the more you have': '你的复制品可以超过1.79e308但是超过后拥有越多复制品复制速率就会越慢',
    'You can only upgrade Infinity Dimensions 50 times, and Replicanti upgrades 40 times.\n ': '你只能升级无限维度50次,和复制品40次\n',
    'You can\'t buy tickspeed upgrades. Infinity power instead multiplies time dimensions with greatly reduced effect.': '你无法购买时间间隔升级,无限力量现在代替时间维度但是以极低的加成',
    'You can\'t gain galaxies normally, but the cost of upgrading your max replicanti galaxies is massively reduced.\n ': '你无法购买普通星系,但是购买复制品星系上限的价格极大的降低了',
    'You complete Infinity Challenges as soon as you unlock them (you get sacrifice autobuyer immediately': '当你解锁无限挑战时将会自动完成该挑战,且立即获得维度献祭自动化',
    'You completed all normal achievements! Congratulations!': '你完成了所有普通成就,恭喜恭喜!',
    'You completed all secret achievements! Congratulations!': '你完成了所有隐藏成就,恭喜恭喜!',
    'You gain': '你获得',
    'You gain 1% of your EP gained on eternity each second.': '每秒会获得直接永恒能得到的永恒点的1%',
    'You gain 1% of your IP gained on crunch each second.': '每秒会获得直接无限能得到的无限点的1%',
    'You gain 1e15 times more IP': '增加1e15倍无限点数获取倍率',
    'You gain 1e25x more IP': '增加1e25倍无限点数获取倍率',
    'You gain 35x more EP': '增加35倍永恒点数获取倍率',
    'You gain 5 times more EP': '增加5倍永恒点数获取倍率',
    'You gain extra RGs based on how high above infinity your replicanti are.': '基于复制品超出无限1.79e308的数量获取更多的复制品星系上限',
    'You gain extra RGs based on your max RGs.': '基于你的复制品星系上限获得更多的复制品上限',
    'You gain Infinity Dimension multiplier based on eternities (x^log4(2x)': '基于你的永恒次数x获得无限维度的倍增(x^log4(2x)',
    'You gain more dilated time based on your meta-antimatter.': '基于元-反物质提升膨胀时间的获取',
    'You gain more EP based on time spent this eternity': '基于此次永恒的进行时间提升永恒点数获取倍率',
    'You gain more Infinity Points based on your galaxies.': '基于星系数量获得更多的无限点数',
    'You gain more Space Shards based on your Eternity Points and Eternal Matter.': '基于永恒点数和永恒物质获得更多的空间碎片',
    'You gain more Space Shards based on your Eternity Points.': '基于永恒点数获得更多的空间碎片',
    'You gain more tachyon particles based on your galaxies.': '基于星系数量获得更多的超光速粒子',
    'You gain replicanti 20 times faster': '复制品复制速率变快20倍',
    'You gain replicanti faster based on your normal galaxies.': '基于普通星系的数量提高复制品复制速度',
    'You gain x1 more infinitied stat (based on dimension boosts': '基于维度提升获得更高的无限次数加成',
    'You get 10 free tickspeed upgrades each.': '每个获得10免费的时间间隔升级',
    'You get 10% more tickspeed upgrades from time dimensions (not considering multiplier increase': '你获得10%来源于时间维度的额外时间间隔升级(不考虑其他倍增)',
    'You get more preons based on your galaxies.': '基于星系数量获得更多的前子',
    'You have': '你有',
    'You have eternitied x times.': '你已经永恒了x次',
    'You have infinitied x times.': '你已经无限了x次',
    'You have made x Antimatter galaxies.': '你拥有x个反物质星系',
    'You have made x antimatter.': '你累计制造了x个反物质',
    'You have made x dimensional boosts/shifts.': '你拥有x个维度提升/转换',
    'You have made x Infinity points.': '你拥有x个无限点数',
    'You have played for': '你玩了此游戏',
    'You have spent x in this eternity': '你在本次永恒花费了x',
    'You have spent x in this Infinity.': '你在本次无限花费了x',
    'You have x galaxy points.': '你拥有x星系点数',
    'You keep half of your replicanti galaxies on infinity': '无限时将会保留一半的复制品星系',
    'You keep your autobuyers on Eternity': '永恒时保留你的自动化',
    '1 Costs: 1e6969 IP': '1 费用: 1e6969无限点数',
    '1% Costs: 1e6969 IP': '1% 费用 1e6969无限点数',
    '10 seconds reward: ON': '10秒奖励:启用',
    '11 Eternities': '永恒11次',
    '1st Dimension Autobuyer': '维度1自动化',
    '2nd Dimension Autobuyer': '维度2自动化',
    '33.3 mins reward: ON': '33.3分钟奖励:启用',
    '3rd Dimension Autobuyer': '维度3自动化',
    '4.5 hours reward: ON': '4.5小时奖励:启用',
    '46% smaller interval': '间隔降低46%',
    '4th Dimension Autobuyer': '维度4自动化',
    '5th Dimension Autobuyer': '维度5自动化',
    '6 hours reward: ON': '6小时奖励:启用',
    '6th Dimension Autobuyer': '维度6自动化',
    '7th Dimension Autobuyer': '维度7自动化',
    '8th Big Rip upgrade is never repealed and capped.': '撕裂宇宙的第8个升级永远不会受限和重置',
    '8th Dimension Autobuyer': '维度8自动化',
    'About': '关于',
    'About ': '关于',
    'achievemult': '成就倍率',
    'Add preset': '增加预设',
    'added to free galaxies amount': '增加免费星系的数量',
    'After-eternity automation': '永恒后自动化',
    'All dimension boost costs are decreased by 30 each.': '每个增加维度提升费用30',
    'All dimension multipliers are disabled except for the multipliers from Infinity power and dimension boosts (to normal dimensions': '对普通维度来说,除了无限力量和维度提升以外失去所有其他增幅',
    'All galaxy costs are decreased by 20 each.': '每个增加星系费用20',
    'All IC3 rules are applied, but only replicanti boosts Infinity Dimensions, free tickspeed upgrades increases IC3 reward 5 times instead, and meta-antimatter does nothing.': '包含无限挑战3的规则,并且只有复制品增幅无限维度,免费时间间隔升级根据无限挑战3的效果增幅5倍,元维度失去效果',
    'All infinitied stat multipliers and generators are disabled.': '无限次数加成失效且禁用了自动获取无限次数',
    'All normal dimension multipliers are disabled except infinity power, but galaxy boost on infinity power is stronger.': '除了无限力量以外普通维度失去所有其他增幅,但是星系对于无限力量的加成更强了',
    'Amount of EP to wait until reset': '到到X永恒点时进行永恒',
    'Amount of eternities to wait until dilate time:\n ': '每永恒多少次开始膨胀时间:\n',
    'Amount of IP to wait until reset': '到达X无限点时进行无限',
    'and': '和',
    'Assign': '分配',
    'Assign all': '全部投入',
    'at': '在',
    'Auto: OFF': '自动:未启用',
    'Automatic Big Crunch challenge, but it affects all dimensions. Meta-dimension boost costs increase slower, but buffs are removed.': '大坍塌自动化挑战,但是会影响所有维度.元-维度提升费用缓慢增长,并且移除了buff.',
    'baby replicants.': '幼儿复制品',
    'Banked eternities are counted in Big Rips.': '在撕裂宇宙中会计算储存的永恒次数',
    'blue Light.': '蓝光',
    'Blue power boosts preon charge production.': '蓝色力量增幅前子充能产量',
    'blue power.': '蓝色力量.',
    'Currently: -': '当前: -',
    'Dark Matter.': '黑暗物质',
    'Decreasing multiplier to IP (1e5 / seconds in infinity': '降低无限点数倍率(1e5/本轮无尽秒数)',
    'Disable Remote Antimatter Galaxies scaling!': '禁用遥远反物质星系的额外花费',
    'Electrons': '电子',
    'Electrons boost is increased.': '电子加成增加了',
    'electrons each galaxy you sacrifice.': '个电子每献祭1星系',
    'electrons.': '电子.',
    'Emperor Dimensions are faster.': '帝国维度变得更快',
    'Eternities and Space Shards boost each other.': '空间碎片和永恒次数彼此互相增幅',
    'Eternity Points slow down Remote Antimatter Galaxies effect.': '永恒点数降低遥远反物质星系的费用',
    'Every 100% of green power effect, they add': '每100%绿色力量,增加',
    'Every quantum': '每次量子',
    'Feed one with quantum food': '用量子食物喂养一个',
    'First Meta Dimension is boosted by dimension boosts.': '维度提升会增幅元维度1的效果',
    'Gain all unstable quarks': '获得所有不稳定的夸克',
    'Gain more neutrinos based on your GHP and color powers.': '基于你的颜色力量和GHP增加中微子的获取数量',
    'Galactic sacrifice when GP gain is over': '当星系点数超过X时进行星系献祭',
    'Galaxies are 50% stronger, but electrons are 30% weaker and normal galaxies are 60% weaker.': '所有星系增强50%,但是电子削弱30%并且普通星系削弱60%.',
    'Galaxies are more effective based on your free galaxies.': '基于免费星系的数量星系增幅星系的加成',
    'galaxies.': '星系.',
    'Get # of quantumed stat below the requirement and then become a ghost for a reward!': '在进入量子世界的次数低于#次时成为幽灵以获取奖励',
    'Go quantum faster than the requirement for a reward!': '基于你进入量子世界的最短时间以获取奖励',
    'Green power boosts odd Emperor Dimensions and preon charge production.': '绿色力量增幅奇数帝国维度效率和前子充能效率',
    'green power.': '绿色力量',
    'green quarks.': '绿色夸克',
    'In Big Rips, each galaxy type boosts differently.': '在撕裂宇宙挑战中,每个星系类型奖励不同',
    'In Big Rips, they boost first Big Rip upgrade strength by': '在撕裂宇宙挑战中,他们增强第一个撕裂宇宙升级奖励by',
    'In Big Rips, they boost IC3 reward strength by': '在撕裂宇宙挑战中,他们增幅无限挑战3奖励by',
    'In Big Rips, they make Tree Upgrades stronger by': '在撕裂宇宙挑战中,他们增幅永恒树奖励by',
    'In Big Rips, they slow down Ghostly Galaxies scaling by': '在撕裂宇宙挑战中,他们降低幽灵星系的价格by',
    'Increasing multiplier to IP (seconds in infinity': '增加无限点数获取倍率(在无限的秒内',
    'Infinity Points boost Normal Dimensions, but all other upgrades except 2nd repeal it.': '无限点数增幅普通维度,但是除了第二个升级其他全部无效',
    'Infinity Points slow down Remote Antimatter Galaxies effect.': '无限点数延迟遥远反物质星系的到来',
    'Infinity points.\n ': '无限点数.',
    'Infinity power slows down Distant Antimatter Galaxies effect.': '无限力量延迟遥远反物质星系的到来',
    'Interval': '间隔',
    'Massively decrease the tickspeed cost multiplier increase to 1.25x.': '大幅度增加时间间隔升级费用至1.25x',
    'Max QK mult': '最大化夸克获取倍率',
    'Meta Dimension Boosts are cheaper.': '元维度提升更便宜',
    'Meta-Dimension Boosts cost less.': '元维度提升费用更低',
    'Meta-dimension boosts slow down Distant Antimatter Galaxies effect.': '元维度提升延迟远距离星系的到来',
    'minute': '分钟',
    'Modifiers': '修改了',
    'Multiplier per ten dimensions boosts Meta Dimensions.': '元维度每购买10次的效果增加了',
    'Muon neutrinos.': '介子 中微子',
    'Nanofield': '纳米领域',
    'Nanofield is faster based on your rewards.': '基于你获取的奖励纳米领域将会更强',
    'Nerfed in Big Rip runs': '在撕裂宇宙挑战中会被削弱',
    'Neutrinos': '中微子',
    'Next': '下一个',
    'normal galaxies.': '普通星系',
    'per': '每',
    'per second.': '每秒.',
    'per second.\n ': '每秒.\n',
    'preon charge.': '前子充能.',
    'preon energy.': '前子能量.',
    'preon power. Next at': '前子力量.下一个在',
    'preons per second and producing': '前子每秒生产',
    'preons per second.': '前子每秒.',
    'preons per second.\n ': '前子每秒.\n',
    'preons.': '前子.',
    'preons/s\n ': '前子/s\n',
    'Production based on current antimatter': '产出基于目前的反物质',
    'Production based on total antimatter produced': '产出基于累计产生的反物质',
    'quark spin': '自旋夸克',
    'Quarks': '夸克',
    'red Light.': '红光',
    'red power.': '红色力量',
    'red quarks.': '红色夸克',
    'Red unstable quarks decay slower based on your RG gluons.': '基于红-绿胶子的降低不稳定红色夸克的衰变速度',
    'red-green gluons.': '红-绿 胶子',
    'Remote galaxy cost scaling is reduced.': '降低了遥远反物质星系的费用',
    'Replicantis boost dilated time production.': '基于复制品数量增幅膨胀时间的产出',
    'replicantis.': '复制品',
    'Replicants': '复制品',
    'Replicated galaxies slow down Dark Matter Galaxies effect.': '复制品星系减慢黑暗物质星系的效果',
    'Require IP from crunch at peak': '需要大坍塌获得最佳无限点',
    'requires': '需要',
    'rewards.': '奖励.',
    'rewards.\n ': '奖励.\n',
    'RG gluons': 'RG胶子',
    'Rotation: None': '旋转:无',
    'Sacrifice': '献祭',
    'Sacrifice affects dilated time production.': '献祭影响膨胀时间的产出',
    'seconds.': '秒',
    'Secrets': '秘密',
    'Slow down Dark Matter Galaxies effect by 13%.': '降低黑暗物质星系效果13%',
    'Slow down Distant Antimatter Galaxies effect by 13.2%.': '降低遥远反物质星系效果13.2%',
    'Slow down Remote Antimatter Galaxies effect by 10%.': '降低远距离星系效果10%',
    'Space Shards boost quark spin productions.': '基于空间碎片增幅自旋夸克的产出',
    'Space Shards.\n ': '空间碎片.\n',
    'Speedrun Milestones': '竞速量子里程碑',
    'Tachyon particles boost the dilated time production more by a little bit.': '超光速粒子对膨胀时间的产出增幅更高一些',
    'Tachyon particles slow down Dark Matter Galaxies effect.': '超光速粒子减慢黑暗物质星系的效果',
    'Tau neutrinos.': '中微子',
    'The effect exponent is increased from': '指数增长增长从',
    'The IP mult multiplies IP gain by 2.3x per upgrade.': '无限点获取倍增提升至2.3x每次升级',
    'The world has collapsed on itself due to excess of antimatter.\n ': '由于充满了反物质世界已经崩溃了.\n',
    'They boost the limit of 14th dilation upgrade from 3.00x to': '第14个膨胀时间升级加成从3.00x到',
    'They decrease free tickspeed upgrade threshold by -': '增加免费时间间隔升级门槛到',
    'They increase TP gain formula exponent from': '指数增加超光速粒子获取公式从',
    'They make "replicate chance boosts itself" stronger from': '增加复制品复制概率增幅自身的效果从',
    'They make Infinite time reward stronger by': '增加到达无限时间的加成到',
    'They slow down Distant Antimatter Galaxies by': '减慢源物质星系到',
    'Tickspeed boosts give 32 free tickspeed purchases each.': '每次购买该加成时间间隔提升给予32个免费的时间间隔升级',
    'Tickspeed cost multiplier increase': '时间间隔费用倍增',
    'times': '次',
    'to': '到',
    'Toggle: ON': '开关:激活',
    'total worker replicants.': '复制品工人',
    'TP gain formula exponent is increased.': '超光速粒子获取公式指数增加',
    'Tree of Decay': '衰变之树',
    'Tree Upgrades': '永恒树升级',
    'ultraviolet light.': '紫外线.',
    'ultraviolet Light.': '紫外线.',
    'Unlock a new boost based on your neutrinos.': '基于你的中微子解锁一个新的加成',
    'Upgrades': '升级',
    'violet Light.': '紫光',
    'WARNING: NOT ENOUGH POWER TO AUTOMATE!': '提醒:没有足够的能量开启自动化',
    'WARNING: This disappears when you reload the game!': '提醒:当你重载游戏时这个会消失',
    'x': 'x',
    'x\n ': 'x\n',
    'x\n ': 'x\n',
    'x and boost preon boost by': 'x和增幅前子加成by',
    'x and in Big Rips, make your tickspeed multiplier boosts sixth Time Dimensions by': 'x和在撕裂宇宙挑战中,使你的时间间隔倍率增幅时间维度6by',
    'x and increase your Neutrino gain by': 'x和增加你的纳米领域产出by',
    'x and reduce preon power threshold increase to': 'x和降低前子能量门槛增加到',
    'x dilated time production': 'x倍膨胀时间产出',
    'x multiplier to all Light strength boosts.': 'x倍所有光能量',
    'x production from all Meta Dimensions': 'x倍产出来源所有元维度',
    'x replicanti.': 'x复制品',
    'x stronger, reduce the cost by 20 less except the first, and decrease the cost multiplier to 30.': 'x倍更强,和降低除了第一个以外的费用20,且增加费用倍率到30',
    'x.': 'x.',
    'x.\n ': 'x.\n',
    'x. (from': 'x.(来源于',
    'xX': 'xX',
    'yellow Light.': '黄光',
    'You can only upgrade Infinity Dimensions 50 times, and Replicanti upgrades 40 times.\n ': '你只能升级无限维度50次和复制品40次.\n',
    'You can\'t gain galaxies normally, but the cost of upgrading your max replicanti galaxies is massively reduced.\n ': '你无法获得普通星系,但是升级复制品最大星系的价格降低了很多',
    'You gain 2x more GHP.': '你获得2倍的GHP.',
    'You gain 2x more quarks.': '你获得2倍的夸克.',
    'You gain 3x more electrons.': '你获得3倍的电子.',
    'You gain 5x more neutrinos.': '你获得5倍的中微子.',
    'You gain more tachyon particles based on your dilated time.': '基于膨胀时间获得更多的超光速粒子.',
    'You gain replicanti faster based on your tickspeed reduction multiplier.': '基于时间间隔降低倍率增幅复制品速度',
    'You have played Bosonic Lab for': '你已经使用波色研究室',
    'You keep your Breaking infinity upgrades on Eternity': '永恒时将会保留打破无限的升级项目',
    'You keep your infinity upgrades on Eternity': '永恒时将会保留无限升级项目',
    'You keep your time studies, dilation upgrades, and mastery studies.': '保留你的时间研究,膨胀时间升级,和专精研究',
    'You need to get Automated Big Crunch interval to 0.1 to be able to break infinity': '你需要将自动大坍塌间隔降低至0.1来打破无尽',
    'You passively generate Infinitied stat based on your fastest infinity.': '基于最快到达无限的时间获取无限次数',
    'You start with replicanti unlocked': '开始游戏时自动解锁复制品',
    'You start with Time Study 192.': '开始游戏时自动解锁时间研究192',
    'You will gain x banked infinities on next Eternity.': '在下次永恒时将会获得x个储存的无限次数',
    'You\'ve gained 0 tickspeed upgrades.': '你拥有0个时间间隔升级',
    'Your achievement bonus affects Time Dimensions': '你的成就加成会影响时间维度',
    'Your best red Light doesn\'t boost this.': '你历史最佳红光不会增幅这个',
    'Your best-in-this-quantum meta-antimatter makes meta-antimatter effect stronger.': '基于本轮量子中你的最佳元维度数量增幅元维度的效率',
    'Your fastest eternity is in x.': '你最快到达永恒是x',
    'Your fastest infinity is in x.': '你最快到达无限是x',
    'Your production is at 100% after purchasing anything, after that it rapidly drops down.': '购买任何东西时的产率是100%随后会极速下降',
    'Your quantum worth is currently': '当前你的量子价值是',
    '\n									(infinitied^1000) Currently': '\n									(到达无限次数^1000) 当前',
    '\n									Reward: Add 0.25x to electron gain multiplier for each Quantum Challenge completed and First & Second Dimensions boost dilated time production. Currently': '\n									奖励: 每一个完成一个量子挑战增加电子获取倍率0.25x,且维度1/2增幅膨胀时间的产出.当前',
    '\n									Reward: All even Meta Dimensions boost all odd Meta Dimensions. Currently': '\n									奖励: 所有偶数元维度增幅所有奇数元维度的效率. 当前',
    '\n									Reward: Boost the reward for these sub-challenges.\n								': '\n									奖励: 提升你所选择的2个挑战的奖励.\n								',
    '\n									Reward: Decrease the free tickspeed upgrade threshold increase. Currently': '\n									奖励: 降低免费时间间隔升级的门槛提升速率. 当前',
    '\n									Reward: Gain more free galaxies for each threshold. Currently': '\n									奖励: 每个门槛可以获得更多的免费星系. 当前',
    '\n									Reward: Infinity power boosts Meta Dimensions at greatly reduced rate. Currently': '\n									降低: 无限力量以极低的效率影响元维度. 当前',
    '\n									Reward: Multiplier per ten dimensions is boosted by dimension boosts. Currently': '\n									奖励: 基于维度提升增加每购买10个维度提升的倍率. 当前',
    '\n									Reward: You gain extra replicated galaxies faster after 100. Currently': '\n									奖励: 当你拥有100个复制品星系后,获得复制品星系的速度更快. 当前',
    '\n									Reward: Your achievement bonus boosts Meta Dimensions. Currently': '\n									奖励: 你的成就加成会增幅元维度的效率. 当前',
    '\n								Translated to': '\n								转化为',
    '\n								You have': '\n								你拥有',
    '\n							Auto-rotate': '\n							自动旋转',
    '\n							Is active': '\n							已激活',
    '\n							You have': '\n							你拥有',
    '\n						- When you get 1 preon power, you will lose preons faster if you are producing preon charge.': '\n						- 如果你正在进行前子充能,每获得1个前子能量你将以更快的速度失去前子.',
    '\n						- When you get 1 preon power, your anti-energy production is 1.41x faster.': '\n						- 每当你拥有1个前子能量,你的反能量产出会加快1.41x',
    '\n						- When you get 1 preon power, your preon charge production is 1.41x slower.': '\n						- 每当你拥有1个前子能量,你的前子充能效率降低1.41x',
    '\n						Good luck for getting more rewards. :)\n					': '\n						祝你好运可以获得更多奖励. :)\n					',
    '\n						Translated to': '\n						转化为',
    '\n						You are getting': '\n						你获得',
    '\n						You have': '\n						你拥有',
    '\n					Current QK gain multiplier': '\n					当前夸克点获取倍率',
    '\n					Feed your normal replicant to become a worker.': '\n					喂养你的普通复制品使其成为工人.',
    '\n					They are gathering': '\n					他们产生',
    '\n					They will become normal replicants at': '\n					他们会变成普通复制品在',
    '\n					To big rip the universe, you need to assign a PC with QC6 & 8 first.': '\n					如果你想撕裂宇宙,需要先进行一个混合量子6/8挑战',
    '\n					Translated to +': '\n					转化为 +',
    '\n					You are getting': '\n					你获得',
    '\n				  Galaxy strength': '\n				  星系力量',
    '\n				Raised to the power of': '\n				提升指数',
    '\n				You are getting': '\n				你获得',
    '\n				You have sacrificed': '\n				你献祭了',
    '\n		If you are stuck in this loading screen, I recommend you to do one of these actions.': '\n		如果你卡在了登录界面,建议你遵循以下操作之一',
    '\n		You may want to check the console for errors (press F12 to view them). If there is any errors, the game won\'t load. Please hard reset (ctrl+f5) when a new patch is applied to fix the errors.\n	': '\n		按F12检查控制台是否报错,如果报错了游戏不会正常开启.按ctrl+F5可以硬重置如果有新的补丁用于修复这个bug.\n	',
    ', multiplier per ten dimensions is currently': ', 当前每10个维度提升倍率',
    ', your preon charge will stop producing energy and anti-energy': ', 前子充能会停止产生能量和反能量',
    '% added green power.': '% 增加绿色力量',
    '% increase in extra replicated galaxies.': '% 增加额外复制品星系.',
    '% increase in galaxy efficiency.': '% 增加星系效率',
    '> 900 Costs: 1e6969 IP': '> 900 花费: 1e6969 无限点数',
    'Aarex\'s Abbreviation System': 'Aarex的缩写系统',
    'About ': '关于',
    'Add Tickspeed Multiplier increase based on your Paradoxes.': '基于你的悖论次数获得时间间隔倍率增幅',
    'Amount of eternities to wait until dilate time:\n ': '经过X次永恒后自动进行膨胀时间',
    'Anti-Preons.': '反前子',
    'Antimatter boosts Paradox Dimensions 1 & 4.': '反物质会提升悖论维度1/4的效果',
    'Antimatter Galaxies are twice as effective': '反物质星系效果增强至2倍',
    'blue quarks.': '蓝色夸克.',
    'Blue unstable quarks decay slower based on your BR gluons.': '基于你的蓝-红胶子降低不稳定蓝色夸克的衰变速率',
    'Bosonic Antimatter.': '波色反物质',
    'Bosonic Battery.': '波色电池',
    'Bosonic Enchants': '波色附魔',
    'Bosonic Extractor': '波色萃取器',
    'Bosonic Lab': '波色研究室',
    'Bosonic Lab is currently running at': '波色实验室当前运行在',
    'Bosonic Runes': '波色符文',
    'Bosonic Speed': '波色速度',
    'Bosonic Upgrades': '波色升级',
    'Bosonic Watts.': '波色瓦特',
    'Bought': '购买',
    'BR gluons': '蓝-红胶子',
    'Branches are faster based on your free galaxies.': '基于免费星系数量提升Branches的速度',
    'Brave Milestones': '勇敢里程碑',
    'Bulk DimBoost Amount': '批量维度提升数量',
    'Buy max Theorems': '最大化购买时间定理',
    'Buy Time Theorems': '购买时间定理',
    'Buying something reduces matter.': '购买一些东西降低正物质',
    'Completed 0 times.': '完成了0次',
    'Cost: ??? Px': '费用: ???悖论点数',
    'Cost: 1 BR gluons': '费用: 1 蓝-红胶子',
    'Cost: 1 EP': '费用: 1永恒点数',
    'Cost: 1 GB gluons': '费用: ',
    'Cost: 1 IP': '费用: 1无限点数',
    'Cost: 1 RG gluons': '费用: 1 红-绿胶子',
    'Cost: 1.00e71 Time Theorems': '费用: 1.00e71时间定理',
    'Cost: 1.02e79 Time Theorems': '费用: 1.02e79时间定理',
    'Cost: 1.10e75 Time Theorems': '费用: 1.10e75时间定理',
    'Cost: 1.32e71 Time Theorems': '费用: 1.32e71时间定理',
    'Cost: 1.59e79 Time Theorems': '费用: 1.59e79时间定理',
    'Cost: 1.66e71 Time Theorems': '费用: 1.66e71时间定理',
    'Cost: 1.99e72 Time Theorems': '费用: 1.99e72时间定理',
    'Cost: 100 BR gluons': '费用: 100 蓝-红胶子',
    'Cost: 100 GB gluons': '费用: 100 绿-蓝胶子',
    'Cost: 100 RG gluons': '费用: 100 红-绿胶子',
    'Cost: 1e20000 antimatter': '费用: 1e20000反物质',
    'Cost: 2 BR gluons': '费用: 2 绿-红胶子',
    'Cost: 2 GB gluons': '费用: 2 绿-蓝胶子',
    'Cost: 2 IP':  '费用: 2 无限点数',
    'Cost: 2 RG gluons': '费用: 2 红-绿胶子',
    'Cost: 2.00e71 Time Theorems': '费用: 2.00e71时间定理',
    'Cost: 2.12e79 Time Theorems': '费用: 2.10e79时间定理',
    'Cost: 2.14e77 Time Theorems': '费用: 2.14e77时间定理',
    'Cost: 2.68e76 Time Theorems': '费用: 2.68e76时间定理',
    'Cost: 2.68e78 Time Theorems': '费用: 2.68e78时间定理',
    'Cost: 2.74e76 Time Theorems': '费用: 2.74e76时间定理',
    'Cost: 20 IP': '费用: 20无限点数',
    'Cost: 4 BR gluons': '费用: 4蓝-红胶子',
    'Cost: 4 GB gluons': '费用: 4绿-蓝胶子',
    'Cost: 4 RG gluons': '费用: 4红-绿胶子',
    'Cost: 4.97e80 Time Theorems': '费用: 4.97e80时间定理',
    'Cost: 40 IP': '费用: 40无限点数',
    'Cost: 5.00e71 Time Theorems': '费用: 5.00e71时间定理',
    'Cost: 500 IP': '费用: 500无限点数',
    'Cost: 6.62e79 Time Theorems': '费用: 6.62e79时间定理',
    'Cost: 6.86e76 Time Theorems': '费用: 6.86e76时间定理',
    'Cost: 7 IP': '费用: 7无限点数',
    'Cost: 8.28e79 Time Theorems': '费用: 8.28e79时间定理',
    'Cost: 8.28e80 Time Theorems': '费用: 8.28e80时间定理',
    'Cost: 8.57e77 Time Theorems': '费用: 8.57e79时间定理',
    'Cost: 80 IP': '费用: 80无限点数',
    'Cost: 9.32e77 Time Theorems': '费用: 9.32e77时间定理',
    'Cost: 9.54e78 Time Theorems': '费用: 9.54e78时间定理',
    'Decrease the number of Dimensions needed for Dimensional Boosts and galaxies by': '增长维度提升和星系需求的维度数量by',
    'dilated time.': '膨胀时间',
    'Distribute all': '分给所有',
    'Don\'t get': '无法得到',
    'eggons': '蛋',
    'Eggons hatch instantly and workers do not consume others.': '蛋会立刻孵化且工人不会消耗其他的',
    'eggons.': '蛋',
    'Eighth Emperor Dimension': '帝国维度8',
    'Eighth Paradox Dimension': '悖论维度8',
    'electron': '电子',
    'electron neutrinos.': '电子 中微子.',
    'Eternity points.': '永恒点数.',
    'Feed (': '喂养(',
    'Fifth Emperor Dimension': '帝国维度5',
    'Fifth Paradox Dimension': '悖论维度5',
    'First Emperor Dimension': '帝国维度1',
    'First Paradox Dimension': '悖论维度1',
    'Fourth Emperor Dimension': '帝国维度4',
    'Fourth Paradox Dimension': '悖论维度4',
    'Gain Anti-Preons': '获得反前子',
    'Galaxies are': '星系有',
    'Galaxies required to always Dimboost': '星系需求X维度时总是进行维度提升',
    'Galaxies required to always tickspeed boost': '星系需求X维度时总是进行时间间隔提升',
    'Galaxies required to always Time Dimension Boost': '星系需求X维度时总是进行时间维度提升',
    'Galaxy exponent boost to Galaxy points gain is buffed, but all Galaxy upgrades that are based on Galaxy points are disabled.': '星系指数提升星系点数获取倍率,但是所有基于星系点数的星系升级被禁用了',
    'Galaxy points boost 2x Infinity Points multiplier upgrades': '星系点数增幅2倍无限点数获取倍率增幅升级',
    'Galaxy points boost Eternity points.': '星系点数增幅永恒点数获取',
    'Galaxy points boost per-10 bought Infinity Dimensions multiplier.': '星系点数增幅每10次购买无限维度的效果',
    'Galaxy points boost Time Dimensions.': '星系点数增幅时间维度',
    'GB gluons': '绿-蓝胶子',
    'Gluons': '胶子',
    'Goal: Infinite IP': '目标: 无限点数到达无限(1.79e308)',
    'Goal: Infinite IP in 1 second or less.': '目标:在1秒内无限点数到达无限(1.79e308)',
    'Goal: Infinite IP in 16 infinities or less.': '目标:在低于16次无限次数内无限点数到达无限(1.79e308)',
    'green Light.': '绿光',
    'Green unstable quarks decay slower based on your GB gluons.': '基于你的绿-蓝胶子降低不稳定绿色夸克的衰变速度',
    'green-blue gluons.': '绿-蓝胶子',
    'Hover to see your current effects': '悬停以查看当前效果',
    'Increase Dimension Boost multiplier': '增加维度提升倍率',
    'Increase the multiplier for buying 10 Dimensions': '增加每购买10个维度的效果',
    'indigo Light.': '靛蓝光',
    'Infinity points.\n ': '无限点数.\n',
    'Infinity power boosts Paradox Dimensions 2 & 5.': '无限力量增幅悖论维度2/5',
    'Infinity Power boosts Time Dimensions.': '无限力量增幅时间维度',
    'Infinity Power effect is stronger based on your Tickspeed Multiplier.': '基于时间间隔倍率增幅无限力量',
    'Matter increases slower.': '正物质增长的更缓慢',
    'Max': '最大',
    'Max enchants': '最大附魔',
    'Max GHP mult': '最大GHP倍增',
    'Max Neutrino mult': '最大纳米领域倍增',
    'Max reduce hatch speed': '最大化降低孵化速度',
    'New preset': '创建新预设',
    'New save': '创建新存档',
    'NG--: OFF': 'NG-2:关闭',
    'NG-: OFF': 'NG-:关闭',
    'NG*: OFF': 'NG*:关闭',
    'NG↑: Linear (↑⁰': 'NG↑: 线性 (↑⁰',
    'NG+: OFF': 'NG+:关闭',
    'NG++: OFF': 'NG+2:关闭',
    'NGUd: OFF': 'NGUD:关闭',
    'NGUd*\': OFF': 'UGUD*关闭',
    'NGUd↑\': Linear\' (↑⁰\'': 'NGUd↑\': 线性\' (↑⁰\'',
    'Notation options': '计数法显示',
    'Numbers on left side': '左侧的数字',
    'Numbers on right side': '右侧的数字',
    'orange Light.': '橙光',
    'per second.\n ': '每秒.\n',
    'preon anti-energy per second.\n ': '前子反能量每秒.\n',
    'preon anti-energy. At': '前子反能量.在',
    'preon charge per second but losing': '前子充能每秒,但是失去',
    'preon energy per second if your preon anti-energy didn\'t reach its limit.\n ': '如果你的前子反能量为到达其限制,前子能量每秒',
    'preons': '前子',
    'preons per second.\n ': '前子每秒.\n',
    'preons/s\n ': '前子/s\n ',
    'Presets': '预设',
    'quarks.': '夸克.',
    'red': '红',
    'red quark spin.': '红自旋夸克',
    'red quarks on next quantum.': '红夸克在下次进量子世界',
    'Replicate interval scaling is 2x slower.': '复制品间隔缩放变慢2倍',
    'Reset': '重新设置',
    'Respecced: NONE': 'Respecced: 无',
    'rewards.\n ': '奖励.\n',
    'Scientific notation': '科学计数法',
    'Second Emperor Dimension': '帝国维度2',
    'Second Paradox Dimension': '悖论维度2',
    'seconds of history': '过去x秒',
    'Select Aarex\'s Modifications': '选择Aarex的修改',
    'Select Aarex\'s Mods II': '选择Aarex的修改II',
    'Select Dark': '选择黑色',
    'Select Dark Metro': '选择黑色Metro',
    'Select Inverted': '选择反向的',
    'Select Inverted Metro': '选择反向的Metro',
    'Select Metro': '选择Metro',
    'Select Normal': '选择普通',
    'Select Star Stream (by YYK': '选择开启蒸汽(by YYK',
    'Select Void (by Soul': '选择虚空(by Soul',
    'Seventh Emperor Dimension': '帝国维度7',
    'Seventh Paradox Dimension': '悖论维度7',
    'Sixth Emperor Dimension': '帝国维度6',
    'Sixth Paradox Dimension': '悖论维度6',
    'Space Shards.\n ': '空间碎片.\n',
    'The world has collapsed on itself due to excess of antimatter.\n ': '世界充满反物质导致崩溃了.\n',
    'They will last': '可以持续',
    'Third Emperor Dimension': '帝国维度3',
    'Third Paradox Dimension': '悖论维度3',
    'Tickspeed multiplier to dimensions is always at 1x, but every tickspeed purchase decreases tickspeed based on galaxies.': '时间间隔倍率对于维度加成始终未1,但是每次购买时间间隔升级会基于星系数增加额外时间间隔',
    'Time Shards boost Paradox Dimensions 3 & 6.': '时间碎片增幅悖论维度3/6',
    'Time Shards speed up Branches.': '时间碎片加快Branches',
    'Time speed is 2x faster.': '速度加快2倍',
    'Triple the amount of Tachyon Particles gained.': '获取的超光速粒子提升3倍',
    'Upgrade enchants': '升级附魔',
    'Use enchants': '使用附魔',
    'was': '是',
    'x Bosonic Antimatter production speed.\n ': 'x波色反物质生产速度.\n',
    'x faster extracting time,': 'x波色萃取器速度',
    'You became a ghost!': '你已完成幽灵化',
    'You can only upgrade Infinity Dimensions 50 times, and Replicanti upgrades 40 times.\n ': '你只能升级无限维度50次和复制品40次.\n',
    'You can\'t gain galaxies normally, but the cost of upgrading your max replicanti galaxies is massively reduced.\n ': '你无法获得普通星系,但是复制品最大星系数量的费用极大的降低了',
    'You failed the challenge, you will now exit it.': '你现在离开将会失败挑战',
    'You gain quark spins faster and all branches are faster based on your tickspeed.': '基于你的时间间隔增加你获得自旋夸克和所有branches的速度',
    'You have 0 banked infinities.': '你有0个储存的无限次数',
    'You have 0 Time Theorems.': '你拥有0个时间定理',
    'You start with the 5th dimension unlocked': '开始游戏时自动解锁维度5',
    'You start with the 6th dimension unlocked': '开始游戏时自动解锁维度6',
    'You start with the 7th dimension unlocked': '开始游戏时自动解锁维度7',
    'You start with the 8th dimension unlocked, and a Galaxy': '开始游戏时自动解锁维度8和1个星系',
    'You will gain 0 banked infinities on next Eternity.': '在下轮永恒你将会获得0个储存的无限次数',
    'Your tickspeed multiplier boosts more if you have more violet Light.)\n ': '你拥有越多紫光你的时间间隔倍率越高',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    //原样
    '': '',
    '': '',

}


//需处理的前缀
var cnPrefix = {
    "(-": "(-",
    "(+": "(+",
    "(": "(",
    "-": "-",
    "+": "+",
    " ": " ",
    ": ": "： ",
}

//需处理的后缀
var cnPostfix = {
    ":": "：",
    "：": "：",
    ": ": "： ",
    "： ": "： ",
    " ": "",
    "/s)": "/s)",
    "/s": "/s",
    ")": ")",
    "%": "%",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^x?\d+(\.\d+)?[A-Za-z%]{0,2}(\s.C)?\s*$/, //12.34K,23.4 °C
    /^x?\d+(\.\d+)?(e[+\-]?\d+)?\s*$/, //12.34e+4
    /^\s*$/, //纯空格
    /^\d+(\.\d+)?[A-Za-z]{0,2}.?\(?([+\-]?(\d+(\.\d+)?[A-Za-z]{0,2})?)?$/, //12.34M (+34.34K
    /^(\d+(\.\d+)?[A-Za-z]{0,2}\/s)?.?\(?([+\-]?\d+(\.\d+)?[A-Za-z]{0,2})?\/s\stot$/, //2.74M/s (112.4K/s tot
    /^\d+(\.\d+)?(e[+\-]?\d+)?.?\(?([+\-]?(\d+(\.\d+)?(e[+\-]?\d+)?)?)?$/, //2.177e+6 (+4.01+4
    /^(\d+(\.\d+)?(e[+\-]?\d+)?\/s)?.?\(?([+\-]?(\d+(\.\d+)?(e[+\-]?\d+)?)?)?\/s\stot$/, //2.177e+6/s (+4.01+4/s tot
];
var cnExcludePostfix = [
    /:?\s*x?\d+(\.\d+)?(e[+\-]?\d+)?\s*$/, //12.34e+4
    /:?\s*x?\d+(\.\d+)?[A-Za-z]{0,2}$/, //: 12.34K, x1.5
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
var cnRegReplace = new Map([
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^(\d+) Royal points$/, '$1 皇家点数'],
    [/^Cost: (\d+) RP$/, '成本：$1 皇家点数'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);